### ISSUE TITLE
Filename does not come automatically while downloading (save as) a file.

### ISSUE THREAD

**Issue by saswatasarkar13** [rafatosta/zapzap#100]
OS:- Fedora 36
DE:- Minimal KDE

If you need any more information, please let me know.

![image](https://user-images.githubusercontent.com/63540311/186076572-7a87e22e-9ed9-421a-a469-bb839300d6d9.png)

**Comment by rafatosta** [comment]
#80

**Comment by saswatasarkar13** [comment]
Got it thanks.
