### ISSUE TITLE
Notificações não estão aparecendo

### ISSUE THREAD

**Issue by HornetoMano** [rafatosta/zapzap#102]
Opa beleza, o app está ótimo, mas está dando um problema. As notificações não estão acionadas quando ligo o app. Tenho que ir dentro do app desselecionar e selecionar novamente estas opções para ativar as notificações normalmente.
![Screenshot_20220823_195024](https://user-images.githubusercontent.com/30988901/186279580-286664fc-3069-48ec-ad85-69eb023f80b0.png)

**Comment by rafatosta** [comment]
Toda vez que o app abre aparece uma mensagem para ativar as notificações e essa ativação é feita automaticamente. Se por um acaso você desativar sem querer não vai aparecer mesmo.

Estou utilizando no momento que envio a mensagem e está funcionando perfeitamente. Logo, acredito que você esteja desativando sem querer quando app abre

**Comment by HornetoMano** [comment]
O meu aparecia antes, mas simplesmente parou de aparecer, vou tentar reinstalar.

**Comment by HornetoMano** [comment]
reinstalei e voltou a funcionar hahah. Muito obrigado.

**Comment by rafatosta** [comment]
> reinstalei e voltou a funcionar hahah. Muito obrigado.

Já aconteceu isso comigo uma vez e achei que eu tinha bugado kkkkk
Foi justamente porque apertei sem querer para não ativar
