### ISSUE TITLE
How to increase font size in ZapZap?

### ISSUE THREAD

**Issue by EkanshdeepGupta** [rafatosta/zapzap#105]
I am running ZapZap v 4.0 on Fedora 36 GNOME 42.3

I have changed the font scaling factor in GNOME Tweaks to 1.75 to make things readable on a 4k monitor.

However, ZapZap does not scale its font accordingly. Moreover, I cannot find settings inside ZapZap to increase font size. Is there a way to increase font size in ZapZap?

Thanks,
Ekansh

**Comment by rafatosta** [comment]
The only way at the moment is to set the following environment variable by Flatseal:

QT_SCALE_FACTOR=1.75

I've marked as improvements to implement this in the future. thanks for reporting

**Comment by rafatosta** [comment]
https://doc.qt.io/qt-5/highdpi.html#:~:text=The%20scale%20factor%20that%20either%20the%20operating%20system%20or%20Qt%20applies.&text=The%20resolution%20used%20to%20convert,192.

I found this here to use autoscale, just haven't been able to test it yet. 

set the QT_AUTO_SCREEN_SCALE_FACTOR environment variable to 1.

**Comment by rafatosta** [comment]
Note: The scale factor is already applied automatically to the application when running outside FlatPak.

Somehow when executing in Flatpak is not recognized or with the defined environment variable, just defining QT_SCALE_Factor manually.

**Comment by rafatosta** [comment]
**When using Wayland the QT_AUTO_SCREEN_SCALE_FACTOR is fully ignored.**

While there is no solution by QT the possible solutions are: 
1. Use X11; or
2. Manually define the QT_SCALE_FACTOR environment variable in Flatseal
