### ISSUE TITLE
Permissão automática para notificações

### ISSUE THREAD

**Issue by RoinujNosde** [rafatosta/zapzap#107]
Tava tendo uns problemas com as notificações, não estava recebendo elas. (#102 relacionado?)
Aí dei uma pesquisada e achei uma forma alternativa de dar a permissão:
```py
self.setFeaturePermission(self.url(), QWebEnginePage.Feature.Notifications, QWebEnginePage.PermissionPolicy.PermissionGrantedByUser)
```

Chamando esse método em `load_finished` dá a permissão automaticamente, o WhatsApp nem precisa pedir e o pop-up não aparece.

Se quiser faço uma PR com a alteração.

**Comment by rafatosta** [comment]
Esses dias tive o problema das notificações sumirem como se tivesse marcado em cancelar, pode até ter sido sem querer ao digitar. Muito obrigado e irei mandar para o flathub ainda hoje
