### ISSUE TITLE
Zoomed in mouse icons

### ISSUE THREAD

**Issue by rene-coty** [rafatosta/zapzap#108]
I use ZapZap on Fedora (= GNOME) and I have noticed that since version ~ 4.0 the mouse pointer seems to be "zoomed in" when the application window is hovered over or when interacting with an item in the window (see screenshots below). I don't know if it is intentional, but it's not very pleasant as it makes the app feeling a bit "out of place" on some desktop environments...

I don't know if it's very explicit in the screenshots 😅 but I really measured it and mouse icons are around 2 or 3 millimeters bigger in ZapZap, which is quite visible on small laptop screens

![Capture d’écran du 2022-09-05 15-50-55-obfuscated](https://user-images.githubusercontent.com/95506494/188472522-711bc07e-bdf4-41d4-a70d-de8e376c5422.png)
Here the mouse pointer in its "normal" size

![Capture d’écran du 2022-09-05 15-51-15-obfuscated](https://user-images.githubusercontent.com/95506494/188472629-9fade580-c8d4-4603-bf47-b133f0efcc82.png)
Here the (bigger) mouse pointer when hovering over the app window

![Capture d’écran du 2022-09-05 15-52-03-obfuscated](https://user-images.githubusercontent.com/95506494/188472721-75e34727-5af0-4f2f-a75e-2d65be772256.png)
Here another icon of the mouse pointer (interacting with an item), which is also bigger than it's normal size

**Comment by rene-coty** [comment]
* It happens whenever the checkbox "ZapZap window" in the system menu is checked or not

**Comment by rafatosta** [comment]
This is not quite an application problem, but the QT framework.
Is related to Wayland and was/is a known problem on Telegram, see more in [Cursor is excessively large on GNOME Wayland HiDPI](https://github.com/telegramdesktop/tdesktop/issues/17457).

**Solutions:**
Change to X11; or
Define by Flatseal the environment variable XCURSOR_SIZE=24
