### ISSUE TITLE
Flatpak application does not follow user theme in Gnome

### ISSUE THREAD

**Issue by rickycec** [rafatosta/zapzap#11]
Hello, I'm on Pop!_Os 21.10 and Gnome 40.
I have the application installed as flatpak and after I changed the theme for the cursor to a custom one, once the cursor goes over the application it's back to the default one.
This doesn't happen with other flapak I have installed (e.g. Telegram or qbtorrent).
Am I missing something?

**Comment by rafatosta** [comment]
Honestly, I have no idea. I don't usually theme the cursor.
Have you tried installing to the system folder instead of the user?

**Comment by rickycec** [comment]
Sorry but I don't have a deep knowledge of flatpaks. I just installed it via the app store present in the distro.
What would be the difference in installing it to system vs user?

**Comment by rafatosta** [comment]
> Sorry but I don't have a deep knowledge of flatpaks. I just installed it via the app store present in the distro.
> What would be the difference in installing it to system vs user?

I referred to the theme being installed in the system folder.

**Comment by rafatosta** [comment]
> Sorry but I don't have a deep knowledge of flatpaks. I just installed it via the app store present in the distro.
> What would be the difference in installing it to system vs user?

I referred to the theme being installed in the system folder.

**Comment by rickycec** [comment]
Ah, you were right. This solved the problem.
Thank you very much!
