### ISSUE TITLE
Site com lista DDI em português

### ISSUE THREAD

**Issue by RoinujNosde** [rafatosta/zapzap#111]
Reparei que o site usado para listar os DDIs está em português; não é muito útil para os usuários de outros países.
Tem um artigo na wikipedia com a [lista completa](https://en.wikipedia.org/wiki/List_of_country_calling_codes#Ordered_by_code).

Ou esse link poderia fazer parte dos arquivos de linguagem.

**Comment by rafatosta** [comment]
Até vi esse link, mas achei sobrecarregado de informações e por isso não o coloquei. De qualquer forma é apenas uma solução temporária por falta de tempo.

Penso que a implementação mais  correta é com um ComboBox com o código dos países e deixar que o usuário defina apenas o DDD + Número.
Se achasse o Regex para cada país ficaria perfeito kkkk

**Comment by RoinujNosde** [comment]
https://github.com/daviddrysdale/python-phonenumbers
Achei essa biblioteca, talvez ajude

**Comment by rafatosta** [comment]
Ajuda, mas é carregar muita coisa para uma única funcionalidade. Já basta o WebEngine que consome bastante recurso.
Penso em fazer da mesma forma que fiz para a [verificação ortográfica ](https://github.com/rafatosta/zapzap/blob/main/zapzap/services/spellCheckLanguages.py). Assim, é só pegar a lista e colocar as informações (DDI, Country, CountryCode), pois é possível pegar o CountryCode do SO.

**Comment by RoinujNosde** [comment]
Eu acho meio trabalhoso reescrever essa lista, deve ter uns 200 códigos.
Uma alternativa seria usar alguma API web pra pegar o código com base no local, ou montar a lista extraindo (web scraping) de algum site.

**Comment by rafatosta** [comment]
Copiar, colar e jogar em uma planilha e ir manipulando no formato do código em python. 
Nada de reescrever
