### ISSUE TITLE
Can't open ZapZap

### ISSUE THREAD

**Issue by gonchez** [rafatosta/zapzap#115]
Hi Rafa,

I have kubuntu 20.04 on my computer. I installed ZapZap via flatpak, and tryed later to run it, but it doesn't open.

This is what I get on terminal when I try to run it:

> gonpi@gonpikubuntu:~$ flatpak run com.rtosta.zapzap
> QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
> qt.webenginecontext: 
> 
> GL Type: desktop
> Surface Type: OpenGL
> Surface Profile: NoProfile
> Surface Version: 3.1
> QSG RHI Backend: OpenGL
> Using Supported QSG Backend: yes
> Using Software Dynamic GL: no
> Using Multithreaded OpenGL: yes
> 
> Init Parameters:
>   *  application-name ZapZap 
>   *  browser-subprocess-path /app/bin/QtWebEngineProcess 
>   *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
>   *  disable-setuid-sandbox  
>   *  disable-speech-api  
>   *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
>   *  enable-threaded-compositing  
>   *  in-process-gpu  
>   *  use-gl desktop 
> 
> [2:10:0915/223827.742300:FATAL:flatpak_sandbox.cc(285)] Your Flatpak version is too old, please update it

Maybe you can help me with this.

Thanks a lot.

**Comment by rafatosta** [comment]
Reason and solution is written at the end of the log:
**Your Flatpak version is too old, please update it**

**Comment by gonchez** [comment]
Sorry for my ignorance about it. I have updated my flatpak and it keeps making the same issue.

**Comment by rafatosta** [comment]
> Sorry about my ignorance. I have updated my flatpak and it keeps making the same issue.

Unfortunately I don't know how to help you either, because I use Fedora. I suggest asking your distro's community for support.

**Comment by rafatosta** [comment]
When you find the solution, post it here, please. This will help others if they split up with the same problem. Thanks

**Comment by gonchez** [comment]
Ok I've been searching and I've found the sollution:

Just adding a flatpak repository
`$ sudo add-apt-repository ppa:alexlarsson/flatpak`

And then update & upgrade.
Later I run the app and it opens and works fine!
I love your app Rafa, thanks so much for your work.

**Comment by rafatosta** [comment]
Thank you very much, your recognition is very important to me.
