### ISSUE TITLE
Request: Ability to turn off spell checking

### ISSUE THREAD

**Issue by pavethem** [rafatosta/zapzap#117]
Since the german spell check doesn't seem to work very well anyways (it underlines very common words),
it would be nice to be able to turn the spell check off altogether. I believe me and a lot of other people would prefer to type like that anyways.

**Comment by rafatosta** [comment]
None of the available options work correctly?

![image](https://user-images.githubusercontent.com/18619894/191811183-6cfb2598-30ff-4cae-974a-cb14c6d4ac49.png)

**Comment by pavethem** [comment]
Unfortunately not, but to be honest I prefer to type with spell check disabled anyways. Nowadays you might use a lot of english words in german sentences and there are always circumstances where the spell check underlines correct words because it doesn't recognize it.

**Comment by rafatosta** [comment]
> Unfortunately not, but to be honest I prefer to type with spell check disabled anyways. Nowadays you might use a lot of english words in german sentences and there are always circumstances where the spell check underlines correct words because it doesn't recognize it.

Got it, no problem.
