### ISSUE TITLE
Feature Request: Lock with a passcode

### ISSUE THREAD

**Issue by bigzooooz** [rafatosta/zapzap#118]
would be nice to have an option to lock the app with a passcode when running in background to add a little bit of privacy

**Comment by rafatosta** [comment]
If you share your PC, isn't it better for everyone to have their own user?
I don't particularly see the point of having a password, but I would like to convince myself of the need for it.

**Comment by harishpillay** [comment]
I know this is an old issue that has since been closed. The use case I have is that when I lock my laptop (I run ZapZap on Fedora via flatpak), I'd want ZapZap to be locked as well. Then when I unlock the laptop, the instance of ZapZap running should ask for password/passcode before it is unlocked.

Here are two screenshots of the Telegram UI. One shows the "unlocked" lock, and when that is clicked, you'd have to provide the local password/passcode to unlock it.  

The "unlocked" lock:
<img width="560" height="129" alt="Image" src="https://github.com/user-attachments/assets/c18d61d5-e490-4602-8192-e68dcc51b914" />

To unlock access:
<img width="560" height="312" alt="Image" src="https://github.com/user-attachments/assets/7bd80fce-1080-4ca5-bdb7-3ed68f7fec0a" />

**Comment by rafatosta** [comment]
> I know this is an old issue that has since been closed. The use case I have is that when I lock my laptop (I run ZapZap on Fedora via flatpak), I'd want ZapZap to be locked as well. Then when I unlock the laptop, the instance of ZapZap running should ask for password/passcode before it is unlocked.
> 
> Here are two screenshots of the Telegram UI. One shows the "unlocked" lock, and when that is clicked, you'd have to provide the local password/passcode to unlock it.  
> 
> The "unlocked" lock:
> <img width="560" height="129" alt="Image" src="https://github.com/user-attachments/assets/c18d61d5-e490-4602-8192-e68dcc51b914" />
> 
> To unlock access:
> <img width="560" height="312" alt="Image" src="https://github.com/user-attachments/assets/7bd80fce-1080-4ca5-bdb7-3ed68f7fec0a" />
> 
> 

Is the native WhatsApp Web feature not working for your use?

**Comment by harishpillay** [comment]
> > I know this is an old issue that has since been closed. The use case I have is that when I lock my laptop (I run ZapZap on Fedora via flatpak), I'd want ZapZap to be locked as well. Then when I unlock the laptop, the instance of ZapZap running should ask for password/passcode before it is unlocked.
> > Here are two screenshots of the Telegram UI. One shows the "unlocked" lock, and when that is clicked, you'd have to provide the local password/passcode to unlock it.
> > The "unlocked" lock:
> > <img alt="Image" width="560" height="129" src="https://private-user-images.githubusercontent.com/73917/573096674-c18d61d5-e490-4602-8192-e68dcc51b914.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzUxNDc2NTUsIm5iZiI6MTc3NTE0NzM1NSwicGF0aCI6Ii83MzkxNy81NzMwOTY2NzQtYzE4ZDYxZDUtZTQ5MC00NjAyLTgxOTItZTY4ZGNjNTFiOTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDAyVDE2MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMDk2OWYyNmE4MGUyYzI2ZTY5ZTg2ODk4NjM3ZTY1MGM2NzcxYjlmNjAyZGJiODM0ZWM3ZjU3OTcwNmYyNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IqgWEbXGuLnslR2sdc5V32NLqC6LT2jkgsE0VONfKR0">
> > To unlock access:
> > <img alt="Image" width="560" height="312" src="https://private-user-images.githubusercontent.com/73917/573096584-7bd80fce-1080-4ca5-bdb7-3ed68f7fec0a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzUxNDc2NTUsIm5iZiI6MTc3NTE0NzM1NSwicGF0aCI6Ii83MzkxNy81NzMwOTY1ODQtN2JkODBmY2UtMTA4MC00Y2E1LWJkYjctM2VkNjhmN2ZlYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDAyVDE2MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNmI4NTk1MzEzMmRkNjFjOGZhMjc4OTYyYjFiOTI0NGEzODViOTlmNjgzNGU0MTJlZjFmNjBiY2Q3NjY5MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GLZzMvpKQ9BKsUl9auCB1hGAss7Jh3dulYZ72oBddyk">
> 
> Is the native WhatsApp Web feature not working for your use?

How would I check for native Whatsapp web? I am only using ZapZap and nothing else.
