### ISSUE TITLE
It closes suddenly after a while

### ISSUE THREAD

**Issue by CleoMenezes** [rafatosta/zapzap#12]
```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/zapzap/engine/browser.py", line 77, in show_notification
    zapzap.service.dbus_notify.show(notification)
AttributeError: module 'zapzap' has no attribute 'service'
```

Version: 2.0

**Comment by zhrexl** [comment]
As a solution to this issue I'd strongly recommend you to change show(notification) to something like notification_show(notification) an then call it like that:

`def show_notification(self, notification): 
    if get_setting('notify_desktop'): 
        notification_show(notification)
`
