### ISSUE TITLE
Chosen style is not applied during start up

### ISSUE THREAD

**Issue by adinan-cenci** [rafatosta/zapzap#120]
I've chosen the dark style, but when starting up the app, it will display the light one.

I need to go to Settings -> Appearance and click a second time on the dark style, even though it is already selected.

Using on Pop Os.

![final](https://user-images.githubusercontent.com/1629643/192142871-65145ec3-5d2b-4fc4-b6c6-e633a293efe4.gif)

**Comment by rafatosta** [comment]
I faced this bug a few days ago. will be fixed soon
