### ISSUE TITLE
Translatable string should not be translatable

### ISSUE THREAD

**Issue by musiclover382** [rafatosta/zapzap#121]
I noticed that in openChatPopup.py, line 86, there is a translatable
`self.btnOk.setShortcut(_("Enter"))`

Is this intentional? Because when I actually translate it, the Enter key stops working as a shortcut

**Comment by rafatosta** [comment]
Not. it was my own mistake 😅

**Comment by rafatosta** [comment]
Thank you so much for putting it in the AUR. Autostart will not work and there are some settings when running outside of flatpak that need to be removed. 

It won't take long to release the fix for that.
