### ISSUE TITLE
flatpak WSL, erro

### ISSUE THREAD

**Issue by elppans** [rafatosta/zapzap#127]
Eu instalei o Ubuntu no WSL e instalei o flatpak nele e ao tentar iniciar, dá um erro:

> F: Running 'bwrap --args 29 zapzap'
bwrap: Can't mount tmpfs on /newroot/dev/shm: No such file or directory

Fiz o seguinte comando para retornar alguma mensagem:

```bash
flatpak --user run -vv com.rtosta.zapzap
```

Esta é a resposta :  

[Pastebin, zapzap_flatpak_vv](https://pastebin.com/raw/W8CWKDrb)

Tem como resolver?

**Comment by rafatosta** [comment]
Olá. Não tenho ideia de como resolver. 
Sugiro procurar suporte da comunidade da sua distribuição, pois parece ser problema do próprio flatpak na distro e não no ZapZap.
