### ISSUE TITLE
Incorrect window shadow

### ISSUE THREAD

**Issue by pdimens** [rafatosta/zapzap#128]
Using Manjaro (Arch) Linux with KDE, I have a very thick flat shadow around the window. I expect this isn't intended behavior. See screenshot below:
![image](https://user-images.githubusercontent.com/19176506/199530763-8fdbdac8-6288-492e-b898-6671724371dd.png)

**Comment by rafatosta** [comment]
It's a problem known to me, but I couldn't stop yet to correct it.One solution is to disable Zapzap window to use the system window.

**Comment by pdimens** [comment]
Thanks for your reply! How does one disable the Zapzap window?

**Comment by rafatosta** [comment]
> Thanks for your reply! I will use the system window in the meantime :) Fantastic work with this project

Thank you very much! ☺️
