### ISSUE TITLE
Disappearing messages problem

### ISSUE THREAD

**Issue by jlaunay** [rafatosta/zapzap#129]
Everytime I click on the zapzap icon in the systray instead of showing the discussion window I get the "disappearing messages" configuration window and I have to quit to go back to the main view.

**Comment by rafatosta** [comment]
This has started to happen to me too and it's already annoying me.As soon as I have time I will make the correction.
Thank you for reporting

**Comment by jlaunay** [comment]
You're welcome, thank you very much for this software!

**Comment by daddy33** [comment]
Hi,
I still have this issue with version 4.4.3 (arcolinux, AUR package, Cinnamon DE, nvidia proprietary drivers).

**Comment by rafatosta** [comment]
> Hi, I still have this issue with version 4.4.3 (arcolinux, AUR package, Cinnamon DE, nvidia proprietary drivers).

This correction has been done for a long time in https://github.com/rafatosta/zapzap/commit/4cb9a14c7537ac976d86ab347e5fad1149908742

**I do not keep the Aur package, so I do not recommend the use!**

**Comment by jlaunay** [comment]
I'm using archlinux as well and I don't experience this problem anymore since the [4cb9a14](https://github.com/rafatosta/zapzap/commit/4cb9a14c7537ac976d86ab347e5fad1149908742) commit.
Zapzap installed from aur using this [PKGBUILD (zapzap-gi)](https://aur.archlinux.org/packages/zapzap-git).
