### ISSUE TITLE
Downloads not saved to folder specified

### ISSUE THREAD

**Issue by cmc302a** [rafatosta/zapzap#13]
First of all, thanks for the great work! 

Using version 2.0 from flatpak (stable), under KDE neon with Plasma 5.23.5; Qt version 5.15.3

I had a hard time clicking on the download arrow of sent files, then a "Save as..." window pops and allows to select a detination for the file... Only to find out, that the file doesn't get downloaded (seeminignly) to the desired destination. Serendipituously, I noticed a sudden popup message (toast) prior to the appearing of the "Save as" window, indicating the attachment had indeed been downloaded, but they get downloaded by default to my "Downloads" folder. It took me a while to figure this out. Can you check into this issue? Default behaviour should be to wait until the user selects download destination in the prompt, not to a default folder.

**Comment by rafatosta** [comment]
It is expected behavior to save to download folder only. Have you tried releasing access to user files through Flatseal?

**Comment by cmc302a** [comment]
Thanks for your response, rafatosta

I tried as you indicated, installed Flatseal and allowed permission to access user files, but it did not change the behavior.

I attach some images to illustrate isssue:

1.- CLick on the arrow under any file attached in WA
2.- Toast message appears (see images, right beneath window prompt), and simultaneously, "Save as..." prompt window opens
3.- User selects destination, clicks on "Save"
4.- File gets saved, but to different destination folder (ie. ~/Downloads)

![imagen](https://user-images.githubusercontent.com/39476825/154316035-ecfe6fa1-54fb-4958-89d6-de681102c6ed.png)

In my opinion, default download directory is OK, as long as no prompt appears, since this is confusing, and also, the user must be advised, that this destination cannot be changed.

**Comment by rafatosta** [comment]
There really is a consistency issue with this functionality. I will look for a solution that encompasses any user folder. I'll be releasing a fix soon. Thank you very much for the feedback

**Comment by rafatosta** [comment]
I managed to get it to save in a different folder, but it still doesn't create just the file. A folder is created with the file inside. 
We already have progress 😊

**Comment by rafatosta** [comment]
Sorted out. Wait, version 2.1 with the fixes already released.
