### ISSUE TITLE
App scrolls to the very end on its own

### ISSUE THREAD

**Issue by adinan-cenci** [rafatosta/zapzap#130]
## Steps to reproduce
Let a conversation accumulate a few messages.
Visit the conversation.
Scroll down, it will work fine, but as you approach the last few message the app will swoop down to the bottom.

## System
PopOs 22.04

**Comment by rafatosta** [comment]
This is a WhatsApp behavior and not from Zapzap.Remember that Zapzap is just a container for the WhatsApp web that brings close features of a native application.
