### ISSUE TITLE
Thumbnails show unusual green boxes

### ISSUE THREAD

**Issue by pdimens** [rafatosta/zapzap#131]
Most thumbnails for images (in any part of the interface) are hidden by these green boxes.

Manjaro Linux. Installation through AUR.

![image](https://user-images.githubusercontent.com/19176506/204650642-2835ab00-a7c6-4062-b56a-2f06c9c1d163.png)

**Comment by rafatosta** [comment]
Do not use it by the AUR, because it is not kept by me.Therefore, I will not solve problems related to the AUR.

Please use the FlatPak version.

I hope you understand, thanks.

**Comment by pdimens** [comment]
Thanks for writing back. I removed the AUR version and installed the Flatpak version and this problem no longer persists.
