### ISSUE TITLE
Feature request: option to export the messages

### ISSUE THREAD

**Issue by rtheodoro** [rafatosta/zapzap#132]
Parabéns pelo app!

Gostaria de sugerir uma nova função: baixar as mensagens (texto, foto, video e audio), além da  informação de quem entrou e saiu).

Essa opção existe no app mobile (pelo menos no android -> Exportar Conversa) e seria massa ter no PC também.

**Comment by rafatosta** [comment]
Esse é um recurso do próprio Whatsapp, então não tenho como implementá-lo. Atualmente, o ZapZap não acessa nenhuma informação das conversas por questão de privacidade e segurança, apenas engloba o Whatsapp Web fazendo seu comportamento similar a um aplicativo nativo (execução em segundo plano, notificações nativas, etc).
Muito obrigado pelo reconhecimento!
Abraços

**Comment by deknos** [comment]
Hi, one question:
so, i could translate your answer, but does your web wrapper store the data of the chats locally? did you inspect if i could export it from the local cache?

**Comment by rafatosta** [comment]
> Hi, one question:
> so, i could translate your answer, but does your web wrapper store the data of the chats locally? did you inspect if i could export it from the local cache?

This is managed by WhatsApp Web itself, and I do not make any modifications or unauthorized access to the original system. 

WhatsApp itself already allows you to back up and export conversations!
