### ISSUE TITLE
Can't open on X11 when a custom xkb layout is being used

### ISSUE THREAD

**Issue by psycake** [rafatosta/zapzap#133]
Hello! I'm using Ubuntu 22.10 with GNOME 43.1 running on X11.

When I try to open ZapZap, I get this error that's preventing it from opening:

![image](https://user-images.githubusercontent.com/52770775/208498002-d782885f-9622-4d82-8e79-8e3b73e3d350.png)

This `/usr/share/X11/xkb/symbols/psy` file is my custom xkb keyboard layout, which does exist in that location. I have added its respective entry in `/usr/share/X11/xkb/rules/evdev.xml`, and it works flawlessly elsewhere (`deb` applications, Snaps, other flatpaks, login screen, recovery terminal, etc.).

When I remove this layout from GNOME settings (leaving the files themselves intact), I no longer get the error and ZapZap works just fine. I can even re-add the layout while ZapZap is open, and then use it inside ZapZap with no problems (though, of course, once I fully close ZapZap and try to re-open it, I get the same error again).

This issue does not occur on Wayland. ZapZap opens just fine with my layout when on Wayland.

Let me know if there's anything I can do to help.

**Comment by rafatosta** [comment]
Unfortunately I don't know how to help you with this problem as it is not directly related to the application.

Have you tried running the application from the source code?

**Comment by psycake** [comment]
Just tried running the application from the source code and this is what I get:

- I get the same issue when trying to open it with the instructions given in "Flatpak Development"
- Upon trying to run it with the instructions given in "Local Development", it runs perfectly fine
