### ISSUE TITLE
Asking to Update Chrome Version

### ISSUE THREAD

**Issue by diasmuchon** [rafatosta/zapzap#136]
Since yesterday, January 26, 2023, the app is asking to update Chrome version. 

[https://i.imgur.com/Pnhwc2O.png](https://i.imgur.com/Pnhwc2O.png)

**Comment by rafatosta** [comment]
> Since yesterday, January 26, 2023, the app is asking to update Chrome version.
> 
> https://i.imgur.com/Pnhwc2O.png

Look #71
