### ISSUE TITLE
When sharing, it does not look for contacts

### ISSUE THREAD

**Issue by mleo33** [rafatosta/zapzap#137]
First of all I want to congratulate you, what you have done is incredible.
I use it a lot, it's the best option I've seen, thank you!

My problem occurs when I want to share a file, when presenting the contact search window it does not work.
I write the name and it does not perform the search.
![busqueda archivos](https://user-images.githubusercontent.com/92488207/215269178-42f28329-1090-4a9a-a7be-8b9b4b5cf780.png)

**Comment by rafatosta** [comment]
This could be a whatsapp web bug. My app, Zapzap, does not make any changes to the official service.
