### ISSUE TITLE
App theme issue on Wayland

### ISSUE THREAD

**Issue by matheucomth** [rafatosta/zapzap#138]
![Captura de tela de 2023-01-29 13-28-52](https://user-images.githubusercontent.com/33396386/215340268-bba307d7-64a6-4213-9b0d-0273a4596530.png)
![Captura de tela de 2023-01-29 13-29-02](https://user-images.githubusercontent.com/33396386/215340277-1bd96d03-9bec-4851-b0d7-828ad5ac8db4.png)

As you can see in the images, there is a visual problem with the mouse cursor in the application, there is an increase in it.

SO: FEDORA 37
UI: Gnome 43.2

**Comment by rafatosta** [comment]
see the solution in  #108
