### ISSUE TITLE
Start manually minimized (not Start ZapZap with the system)

### ISSUE THREAD

**Issue by deivi98** [rafatosta/zapzap#140]
Hi there,

Just discovered this repo today. It is amazing, just what I needed. There is just one thing I am missing, and that is the capability to start minimized.

I have found this portion of code which seems to manage window's behaviour, however, either `zapzap` command is not passing arguments to python program or I am missing something. Also, I think adding regular command help (`zapzap --help`) would be useful.

https://github.com/rafatosta/zapzap/blob/4394fc4c3073b07191b7e2b2a8364cc62c6a5e21/zapzap/__main__.py#L65-L71

Thanks in advance, great work!

**Comment by rafatosta** [comment]
It's strange it's not working. As soon as possible I will analyze and make the correction. Thanks for the feedback and using my app 😊

**Comment by rafatosta** [comment]
The minimized start is working properly.Are you running via flatpak?

**Comment by deivi98** [comment]
Nope, I installed the package via [AUR repository](https://aur.archlinux.org/packages/zapzap), maybe it is a previous version?

Also, what command are you using to start minimized? I was trying `zapzap --hideStart`

**Comment by rafatosta** [comment]
> Nope, I installed the package via [AUR repository](https://aur.archlinux.org/packages/zapzap), maybe it is a previous version?
> 
> Also, what command are you using to start minimized? I was trying `zapzap --hideStart`

Do not use the AUR version, as it is not kept by me and presents several errors because it is not developed thinking to execute outside Flatpak.

**Comment by deivi98** [comment]
Thanks for letting me about flatpak. However, it is still not working for me.

After running `flatpak run com.rtosta.zapzap --hideStart`, window stills pop up.

**Comment by rafatosta** [comment]
> Thanks for letting me about flatpak. However, it is still not working for me.
> 
> After running `flatpak run com.rtosta.zapzap --hideStart`, window stills pop up.

Iso here is working perfeitally.I recommend stirring qualquer configurações feitas previously na pasta autosart ou até tudo da paste do app em .var

**Comment by deivi98** [comment]
After trying a couple of things, I have discovered it does work, but if only if option `Start ZapZap with the system` is enabled. I want to start ZapZap minimized, but not when the system starts. And other people might even want to start it with the system minimized but with a command instead of activating option in UI.

The issue is command `flatpak run com.rtosta.zapzap --hideStart` does not work if `Start ZapZap with the system` option is disabled. From my point of view, I don't see why one thing is related to the other.

To me, the solution to this is changing line 68 from an **and** to an **or**:

https://github.com/rafatosta/zapzap/blob/4394fc4c3073b07191b7e2b2a8364cc62c6a5e21/zapzap/__main__.py#L65-L71

**Comment by rafatosta** [comment]
There is no one because, I just did it that way. I did not see sense to start manually told.

**Comment by deivi98** [comment]
Please merge :)
