### ISSUE TITLE
Permitir alterar o avatar

### ISSUE THREAD

**Issue by tiagocasagrande** [rafatosta/zapzap#142]
Quando se usa mais de uma conta/usuário é permitido adicionar um nome, mas esse nome não é exibido em nenhum local. 
Não há como saber se forma rápida qual é o usuário, pois o avatar também não permite ser alterado.

Recomendação, title com  nome do usuário, ou permitir alterar o avatar.
![tJfXIiH](https://user-images.githubusercontent.com/17714821/225168640-49f08fa0-3b53-4199-8489-117990185930.png)

**Comment by rafatosta** [comment]
Olá, Tiago.
O nome do usuário já é exigido ao colocar o mouse sobre o ícone.
![image](https://user-images.githubusercontent.com/18619894/225305735-d87ffcbc-6c0a-4969-b627-12314c277af3.png)

Colocar uma imagem é uma funcionalidade que penso para o futuro. =D

**Comment by tiagocasagrande** [comment]
Perdão, o meu realmente não estava aparecendo. Realizei a re-instalação, tudo ok.
Desculpe, mas fica pela dica do avatar personalizado.
Abraço!
