### ISSUE TITLE
Missiong chat dropdown 

### ISSUE THREAD

**Issue by bayurmdn** [rafatosta/zapzap#143]
I'd like to do quick action chat but seems button dropdown is missing. 
![Quickaction](https://user-images.githubusercontent.com/52649291/225210794-695faf08-140a-492c-ad01-2ed60041b83e.png)

**Comment by rafatosta** [comment]
ZapZap is just a WebApp with some features to make it look like a native app. I haven't made any changes to its functionality, so any bugs about the service there's not much you can do.
