### ISSUE TITLE
a janela "gruda" no meu cursor ao tentar arrastar o app pela decoração da janela

### ISSUE THREAD

**Issue by 4nyNoob** [rafatosta/zapzap#145]
eu normalmente uso uma tecla de atalho para arrastar meus aplicativos pela tela, mas as vezes eu ainda arrasto as coisas pela decoração da janela (a barra de cima das janelas com o nome do app) e apenas o zap zap gruda no meu cursor, eu clico pra arrastar e solto mas eu preciso clicar novamente pra que o app se solte do meu cursor, ao usar uma tecla de atalho isso não acontece

**Comment by rafatosta** [comment]
> eu normalmente uso uma tecla de atalho para arrastar meus aplicativos pela tela, mas as vezes eu ainda arrasto as coisas pela decoração da janela (a barra de cima das janelas com o nome do app) e apenas o zap zap gruda no meu cursor, eu clico pra arrastar e solto mas eu preciso clicar novamente pra que o app se solte do meu cursor, ao usar uma tecla de atalho isso não acontece

Está usando em Wayland ou X11?

**Comment by 4nyNoob** [comment]
> Está usando em Wayland ou X11?

X11

**Comment by rafatosta** [comment]
> > Está usando em Wayland ou X11?
> 
> X11

Certeza que está no Plasma, pois não estou tendo esse comportamento no gnome. 

Muda para a decoração do sistema e verifica se o comportamento continua, por favor

**Comment by 4nyNoob** [comment]
```
OS: KDE neon 5.27 x86_64
Kernel: 5.19.0-35-generic
DE: Plasma 5.27.3
GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate 
```

mudando a decoração de janela do KDE não altera a decoração do zap zap (ao menos q eu tenha q reiniciar o app)  sempre continua a mesma decoração, meno se eu modar o tema do GTK nas opções do KDE
![image](https://user-images.githubusercontent.com/113947854/227682184-603585f9-1951-47a9-9dbd-ad1bc89cdf76.png)

**Comment by rafatosta** [comment]
> ```
> OS: KDE neon 5.27 x86_64
> Kernel: 5.19.0-35-generic
> DE: Plasma 5.27.3
> GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate 
> ```
> 
> mudando a decoração de janela do KDE não altera a decoração do zap zap (ao menos q eu tenha q reiniciar o app) sempre continua a mesma decoração, meno se eu modar o tema do GTK nas opções do KDE
> 
> edit: o zap zap é o único app com esse estilo de decoração de janela ![image](https://user-images.githubusercontent.com/113947854/227682184-603585f9-1951-47a9-9dbd-ad1bc89cdf76.png)

Você muda nas configurações do próprio ZapZap.

**Comment by 4nyNoob** [comment]
![image](https://user-images.githubusercontent.com/113947854/227731404-3c4d668e-917d-4168-aabf-71ce0fcad899.png)

acabei de desligar a janela do zap zap por completo e agr tá tudo perfeito na questão da decoração de janela, o app já tá usando a decoração padrão do KDE como os outros e não gruda mais no meu mouse :)

**Comment by rafatosta** [comment]
> ![image](https://user-images.githubusercontent.com/113947854/227731404-3c4d668e-917d-4168-aabf-71ce0fcad899.png)
> 
> acabei de desligar a janela do zap zap por completo e agr tá tudo perfeito na questão da decoração de janela, o app já tá usando a decoração padrão do KDE como os outros e não gruda mais no meu mouse :)

Lembrei que já tinha visto esse comportamento há muito tempo atrás quando fiz um teste no Plasma, mas depois de algumas atualizações parou. Usei para Fedora para o teste, mas como não uso o plasma não sei como as versões variam em relação as outras distros. 

Dei uma olhada aqui no meu código e parece ser algo com o próprio Qt e não sei se vale o esforço para arrumar isso no momento. 

Que bom que conseguiu resolver.
Abraços
