### ISSUE TITLE
Zoom / Font size

### ISSUE THREAD

**Issue by deivi98** [rafatosta/zapzap#146]
Hi there,

I have quite a big screen and I need to zoom in to read without effort. It is not a big deal but it would be amazing if ZapZap could save window / chromium's zoom and set it every time the app starts. An alternative / addition to this would be to be able to modify font size.

I am open to implement it myself, so if anyone has any ideas / suggestions let me know!

Great app btw, I have been using it for a while now and I am very happy.

**Comment by rafatosta** [comment]
> Hi there,
> 
> I have quite a big screen and I need to zoom in to read without effort. It is not a big deal but it would be amazing if ZapZap could save window / chromium's zoom and set it every time the app starts. An alternative / addition to this would be to be able to modify font size.
> 
> I am open to implement it myself, so if anyone has any ideas / suggestions let me know!
> 
> Great app btw, I have been using it for a while now and I am very happy.

This functionality exists and is working perfectly.

**Comment by deivi98** [comment]
For some reason it was not working for me, but it is now. Apologies for opening the issue. Closing.
