### ISSUE TITLE
Does not recognize the microphone

### ISSUE THREAD

**Issue by RogerioTDS** [rafatosta/zapzap#147]
Hello, could you add microphone support in zapzap?
When trying to record audio it does not recognize my microphone.
![Captura de tela de 2023-04-05 23-03-54](https://user-images.githubusercontent.com/120617835/230255005-d6786635-bb88-451d-b8c0-0353d092b174.png)
I opened whatsapp web in firefox and it recognizes the microphone normally.
In firefox, before recording an audio, a whatsapp web dialog box appears, asking for permission to access the microphone - this box does not appear in zapzap - I believe this is the problem!
![Captura de tela de 2023-04-05 23-11-39](https://user-images.githubusercontent.com/120617835/230255057-c15b48c5-5448-4b89-8785-acbc93eb73e3.png)

Thanks in advance for your attention!

**Comment by rafatosta** [comment]
Tenta reinstalar, pois não faz sentido esse problema.
Está utilizando em Flatpak? Fez alguma modificação pelo Flatseal?

Aqui está funcionando perfeitamente
![image](https://user-images.githubusercontent.com/18619894/230492369-862b5cd3-044d-4b6a-91b4-6054950b4312.png)

**Comment by RogerioTDS** [comment]
Olá, obrigado pela resposta.
Podemos conversar em português aqui, então. Valeu!
Eu estava usando a versão do AUR do arch, agora passei para a flatpak. 
O problema comigo persiste.
Eu não sabia o que era o Flatseal. Aí fui pesquisar e instalei.
Vi que as permissões, tanto para microfone quanto para a webcam, não estão ativadas.E não consigo ativá-las lá!
Você saberia me dizer algum meio de fazer isto?
Desde já, grato pela atenção!
![image](https://user-images.githubusercontent.com/120617835/230740217-82abeb6b-2d87-49d5-8e1b-b2450a1ce49a.png)

**Comment by rafatosta** [comment]
O Zap do AUR é muito bugado e instável, pois, além de não ser mantido por mim, não construir o zap para funcionar fora do flatpak (para facilitar a manutenção nas diversas distros).

Realmente no Flatseal não fica disponível essas opções, pois não usa diretamente os portais para acessar os dispositivos.
![image](https://user-images.githubusercontent.com/18619894/230920844-eec7a1fa-6a71-4b5d-91a8-bdd22bbffdc2.png)

Nunca vi nem tive algum problema parecido o seu. Não sei se pode ser algo no Arch ou nas configurações do flatpak. 
Uso o Fedora e nunca mudei nenhuma configuração no flatpak.
Estou nessa versão
![image](https://user-images.githubusercontent.com/18619894/230921210-9b04d4fd-c588-4839-8078-2f8c4249e18b.png)

**Comment by RogerioTDS** [comment]
Olá, desculpe a demora na resposta.
Realmente, não é o zapzap, testei aqui no fedora e no opensuse e, em ambos, o problema persiste...então, é meu hardware.
Meu microfone é usb virtual, talvez seja esse o problema. No telegram e em outros apps tem como selecionar o microfone em uso...acho que por isto funciona lá.
Já tentei várias permissões no flatseal e não consigo fazê-lo reconhecer...creio que tenho que adicion-lo em algum lugar ali.
Outra, se puder me dar uma luz: usando a versão flatpak agora - já que antes eu usava a do AUR - eu não consigo colar nada da área de transfência no zapzap(na versão do AUR eu conseguia), saberia me indicar uma possível solução para isto?
Desde já, grato pela atenção!

**Comment by rafatosta** [comment]
> Olá, desculpe a demora na resposta.
> Realmente, não é o zapzap, testei aqui no fedora e no opensuse e, em ambos, o problema persiste...então, é meu hardware.
> Meu microfone é usb virtual, talvez seja esse o problema. No telegram e em outros apps tem como selecionar o microfone em uso...acho que por isto funciona lá.
> Já tentei várias permissões no flatseal e não consigo fazê-lo reconhecer...creio que tenho que adicion-lo em algum lugar ali.
> Outra, se puder me dar uma luz: usando a versão flatpak agora - já que antes eu usava a do AUR - eu não consigo colar nada da área de transfência no zapzap(na versão do AUR eu conseguia), saberia me indicar uma possível solução para isto?
> Desde já, grato pela atenção! 

Notei esse comportamento do copiar e colar apenas quando o ZAP está em Wayland. Mesmo assim, são apenas de alguns apps. Do editor de texto para o ZAP não vai de jeito nenhum. Podem, do navegador, do Nautilus, GS vão. Depois vou abrir uma issue e ver se alguém mais reporta esse comportamento em outros ambientes

**Comment by RogerioTDS** [comment]
Obrigado pela atenção.
Tu já está ciente do comportamento, então. Realmente, estou usando o Wayland!
Novamente, obrigado pela atenção.
