### ISSUE TITLE
App stopped remembering window state when opening new window

### ISSUE THREAD

**Issue by Tuba2** [rafatosta/zapzap#148]
Previously, when I closed the window and then opened it again from the systray indicator, the new window would open in the same position, size and state — in case it was maximized, the new window would be opened already in the maximized state.

It doesn't happen anymore: now, whenever I close a window and open a new one, the app will only remember the position and some elements of the size (very inconsistently), but never the maximized state. in fact, whenever you close the window in a maximized state, when you open a new window it will open in the default position, size and state — a rectangular window, almost centered.

I'm using the Flathub flatpak version of ZapZap on Fedora 38, with the system native window (instead of the app's own style) and hidden menu bar, on GNOME 44.

Things were working fine on Fedora 37 and GNOME 43.
The behavior changed as soon as I updated to Fedora 38 and GNOME 44.

I recorded my screen so you can see it in action (don´t mind the content, there's no sensitive information being shown):

[Gravação de tela de 2023-04-18 17-00-01.webm](https://user-images.githubusercontent.com/82492785/232892158-c2a563f2-aa8f-45fb-8efc-a0dfeb13dd47.webm)

**Comment by Tuba2** [comment]
Com a AppIndicator tá funcionando certinho! Hahaha

Mas putz, entendo, mó complicado

Relatei aqui pra cê poder saber certinho, e ajeitar quando/se der.

Manjo nada de código, mas, no que eu puder ajudar, tamo aí!

**Comment by rafatosta** [comment]
Tranquilo... 
Voltei a usar o ZAP em Wayland e parece funcionar bem. Eu não sou de ficar redimensionando a janela, mas vou observar o comportamento. Pode ser que algo mudou a forma de pegar os valores no novo gnome. 

O pior é que uso a função do próprio Qt. Ou eu terei que mudar algo ou esperar o Qt atualizar.

**Comment by rafatosta** [comment]
Nota: Este problema acontece apenas ao executar o ZapZap em Wayland. Em x11 funciona perfeitamente.

**Comment by rafatosta** [comment]
SOLVED
