### ISSUE TITLE
Doesn't work on Ubuntu 23.04

### ISSUE THREAD

**Issue by bukbr** [rafatosta/zapzap#149]
Doesn't work properly on Ubuntu 23.04, crashes.

**Comment by bukbr** [comment]
I used it on 22.04 without problems, after upgrading to 23.04 and the problems started:

- The screen even opens and works until you click on a contact, then it freezes and nothing else happens
- When trying to resize the screen it's also another problem, on the second or third attempt it crashes and won't work anymore
- The only way out is to close the app

Had to find a replacement until fixed unfortunately.

**Comment by rafatosta** [comment]
Your report remains vague.  If it was after updating Ubuntu, it looks more like something from the update than from ZapZap.

**Comment by bukbr** [comment]
Exactly! Something in the new ubuntu 23.04 prevents ZapZap from working correctly.

**Comment by rafatosta** [comment]
So it's waiting for Ubuntu to make the two corrections due

**Comment by bukbr** [comment]
An additional note... all the other apps I have installed here (over 20) worked fine in the new version of Ubuntu. Will they make adjustments for ZapZap to run correctly? I will wait...
