### ISSUE TITLE
Zapzap does not run when NVIDIA graphics enabled

### ISSUE THREAD

**Issue by cmc302a** [rafatosta/zapzap#15]
Using version 2.2 from flatpak (stable), under KDE neon with Plasma 5.23.5; Qt version 5.15.3.
nvidia driver version: 510.54

When running desktop session with integrated graphics (intel) under prime-select, zapzap runs fine. However, when enabling discrete graphics (nvidia) via prime-select, zapzap closes instantly.

**Comment by rafatosta** [comment]
I don't have NVidia to test. Please run via terminal and send the generated error.

**Comment by cmc302a** [comment]
Sure.

When launching via terminal, this is the output (verbose):

$ flatpak run com.rtosta.zapzap -v
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
Could not initialize GLX

Hope this helps. Glad to test if you require.
