### ISSUE TITLE
Application freezes after moving it across the screen

### ISSUE THREAD

**Issue by joaopedroaat** [rafatosta/zapzap#152]
Application freezes after moving it across the screen and only returns to normal after minimizing it

https://github.com/rafatosta/zapzap/assets/37046927/b5d2798b-4b7f-4baf-94a4-5acf6aeb9914

Using Fedora 38

**Comment by rafatosta** [comment]
Olá, Pedro. 

Ao desativar a extensão de animação da janela o problema continua?

**Comment by joaopedroaat** [comment]
Sim, continua

**Comment by rafatosta** [comment]
Também utilizo o F38 e esse problema não acontece. 
Parece que você modifica bastante, logo o problema pode ser as extensões que utiliza.

[Gravação de tela de 2023-05-12 08-32-44.webm](https://github.com/rafatosta/zapzap/assets/18619894/7981ee68-4068-4a19-8fb3-51b8e78a4c96)
