### ISSUE TITLE
Pagina inicial 

### ISSUE THREAD

**Issue by dinhokusanagi** [rafatosta/zapzap#158]
Todas as vezes que o aplicativo vai para pagina inicial aparece essa mensagem na tela.

![Captura de tela de 2023-06-12 14-31-50](https://github.com/rafatosta/zapzap/assets/43162113/ab13e14d-f129-4a09-8345-94001f63dfc8)

Fedora Silverblue

**Comment by rafatosta** [comment]
Notei isso apenas quando está aberto em algum grupo. 
Vou arrumar um tempinho para ajustar isso.
Obrigado pelo feedback
