### ISSUE TITLE
ZapZap flatpak tem permissões inseguras

### ISSUE THREAD

**Issue by guiopen** [rafatosta/zapzap#159]
![Captura de tela de 2023-06-13 00-22-14](https://github.com/rafatosta/zapzap/assets/94094527/1a989404-36bf-4a47-be76-5cf1901ade67)

![Captura de tela de 2023-06-13 00-25-31](https://github.com/rafatosta/zapzap/assets/94094527/347b242e-b96e-4a6a-8c83-1175c4f0f522)

O app tem acesso a todos os arquivos do sistema (filesystem=host) sem necessidade. A permissão pode ser removida através do flatseal e o app continua funcionando normalmente.

**Comment by rafatosta** [comment]
Se desmarcar essa opção perderá a funcionalidade de arrastar e soltar arquivos para dentro de uma mensagem. 
Deixo essa opção marcada, pois nem todos possuem conhecimento do flatseal e podem achar que o app tem problema. Assim, com a opção marcada, é possível acessar todos os arquivos do seu sistema, o que incluem HD externos, pendrives ou armazenamento secundário instalado no Pc. 

Garanto que não há de se preocupar, mas se mesmo assim não confiar no app, pode desmarcar sem problema. Lembrem-se de que o acesso a envio e armazenamento de arquivos pode ser comprometido. Faça por sua conta em risco.
