### ISSUE TITLE
Right click for menu on messages.

### ISSUE THREAD

**Issue by Ben7230** [rafatosta/zapzap#160]
It would be nice to able to right click on a message and get the options menu, rather than having to click on the little down arrow. This could maybe be a setting that could be toggled for some people that do like the little down arrow.

This would work on all messages, photos, videos, documents.

**Comment by rafatosta** [comment]
I confess that I did not understand the need for this if there is already an option and it works. 
Just the desire to click with the right button instead of the left?

**Comment by rafatosta** [comment]
What is being executed is WhatsApp Web (https://web.whatsapp.com/), so this feature should be implemented there and not here.Zapzap only packs the WhatsApp Web and inserts some refusal to look like a native application.
