### ISSUE TITLE
Save option for status media

### ISSUE THREAD

**Issue by Ben7230** [rafatosta/zapzap#161]
It would be nice to be able to right click on a status and be able to download it to my media folder. 

I was trying to find were the status files/media are located and was unable to locate them. Maybe somebody could help me with that location.

**Comment by rafatosta** [comment]
Hello, this is a webapp that I left looking like a desktop application. So these features need to be native to whatsapp web.
I am against inserting unofficial features to avoid security issues.

**Comment by Ben7230** [comment]
Hi, 

Yes, I was aware of that and I understand.

Just thought I would ask! :)
