### ISSUE TITLE
open ws links with zapzap

### ISSUE THREAD

**Issue by Serg10** [rafatosta/zapzap#171]
how i can open ws links from any web with zapzap?
by default my ubuntu opens in webversion of browser...

**Comment by rafatosta** [comment]
Zapzap supports link redirection. Check in your browser options if you checked the "don't ask me again" or "remember this option" box.

**Comment by rafatosta** [comment]
I checked and is working perfectly
![image](https://github.com/rafatosta/zapzap/assets/18619894/872c110f-6132-4584-b06e-34fd4eff6f5e)

**Comment by Serg10** [comment]
thanks but i cant find where my broeser (chrome) saves that config to disable it :

**Comment by Serg10** [comment]
I have reset chrome and I have managed to get that box to appear but when I click on open with zapzap nothing happens :(

<a href="https://ibb.co/dgJXvjY"><img src="https://i.ibb.co/ySBKCdj/Captura-desde-2023-08-01-21-55-11.png" alt="Captura-desde-2023-08-01-21-55-11" border="0"></a>

**Comment by rafatosta** [comment]
Are you using Flatpak?
What distribution?

**Comment by Serg10** [comment]
yes, installed from flatpak

<a href="https://ibb.co/VqyF38V"><img src="https://i.ibb.co/cr5WxdJ/Captura-desde-2023-08-02-11-31-14.png" alt="Captura-desde-2023-08-02-11-31-14" border="0"></a>

distro = Ubuntu 22.04.2 LTS (jammy)

**Comment by fabioraitz** [comment]
Clicking to open link on Zapzap from the browser brings Zapzap window to foreground but wont open the chat corresponding to the link.
