### ISSUE TITLE
Broken System when try move windows when "Open new chat" is open 

### ISSUE THREAD

**Issue by Mazuricio** [rafatosta/zapzap#173]
If you try to move the main window when "Open new chat" is open, the system crash and go to login system 

System:
  Kernel: 6.4.6-76060406-generic x86_64 bits: 64 Desktop: GNOME 42.5
  Distro: Pop!_OS 22.04 LTS
Machine:
  Type: Portable System: Dell product: Inspiron 5537 v: A12
  Mobo: Dell model: 0YK7DY v: A00 
CPU:
  Info: dual core model: Intel Core i7-4500U bits: 64
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel
  Device-2: AMD Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 M430 Radeon 520 Mobile]

Portuguese: 

Quando eu tento mover a janela principal quando o "abrir nova conversa" está aberto o sistema quebra e volta para a tela de login do sistema, consigo reproduzir facilmente esse bug

**Comment by rafatosta** [comment]
Executei o app em flatpak, em rpm e diretamente do código e não consegui reproduzir esse erro.

**Comment by Mazuricio** [comment]
To a 2 dias q meu pc acontecia esse problema, não tinha entendido que era por causa do zapzap, até hoje acontecer 2 vezes seguidas e entendi o padrão, reproduzi 2 vezes antes de enviar.
Agora não ocorre mais :\ 
Obrigado pela atenção e pelo app.

**Comment by rafatosta** [comment]
> To a 2 dias q meu pc acontecia esse problema, não tinha entendido que era por causa do zapzap, até hoje acontecer 2 vezes seguidas e entendi o padrão, reproduzi 2 vezes antes de enviar.
> Agora não ocorre mais :\ 
> Obrigado pela atenção e pelo app. 

Obrigado. 
É muito estranho esse problema e resultar em "quebra" do sistema e encerrar a sessão. 

Deixe em observação e qualquer coisa executa o app via terminal e tenta consegue algum log. Se for algo que possa ser feito no app para evitar, farei um fix. 

Abraços
