### ISSUE TITLE
Feature Request: Start minimized

### ISSUE THREAD

**Issue by Operius73** [rafatosta/zapzap#174]
Hi, it would be nice if zapzap would have the option to start minimized in the system tray. I have it set to start at login but it is a little (very little) annoying to close the window every time. Thank you.

**Comment by Operius73** [comment]
You're right! I feel stupid! 😄

Just to be clear for others, I had added zapzap to the list of programs to start at login myself via the gnome-tweaks tool. Then it does not start up minimized. But it does when I check the box to start automatically in the build in settings menu.

Thank you Rafatosta for your answer, and for making zapzap!

**Comment by rafatosta** [comment]
Use Zapzap's native option for system initialization.

Thanks

**Comment by wokawoka** [comment]
Hello,
isn't there a command to start Zapzap minimized?
It would be very useful to start it minimized even when not on startup.
And in my case Zapzap's native option "Start Zapzap with the system" launches Zapzap minimized but without notwork access (see screenshot below).
I'm on Ubuntu 24.04 and KDE 5.27

Thank you very much for this very useful tool.

![image](https://github.com/rafatosta/zapzap/assets/7824587/3b5cddef-cdbe-44b6-8b28-baa24aec51ae)

**Comment by rafatosta** [comment]
> Hello, isn't there a command to start Zapzap minimized? It would be very useful to start it minimized even when not on startup. And in my case Zapzap's native option "Start Zapzap with the system" launches Zapzap minimized but without notwork access (see screenshot below). I'm on Ubuntu 24.04 and KDE 5.27
> 
> Thank you very much for this very useful tool.
> 
> ![image](https://private-user-images.githubusercontent.com/7824587/346063014-3b5cddef-cdbe-44b6-8b28-baa24aec51ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzY0ODIsIm5iZiI6MTcyMDE3NjE4MiwicGF0aCI6Ii83ODI0NTg3LzM0NjA2MzAxNC0zYjVjZGRlZi1jZGJlLTQ0YjYtOGIyOC1iYWEyNGFlYzUxYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMTA0MzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmExZTAxMzBkZjM0MDRmMDNjMjlhMjQwODY5ODQwZjA3MTRiMjkyZTMxOGRjN2UwYWZiYjM3N2QyYTI2ZWRkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PVmMbzKOVQHbc_BA4WJM_yfimvPSSPNUbvN5zR43vvY)

It doesn't make any sense to click on the icon and run with the window hidden.

Regarding the internet, I believe your distro is starting apps before the internet itself. Maybe some personal configuration, because here, with everything standard, it works.

**Comment by wokawoka** [comment]
I think that clicking on the icon to launch the program minimized would still be useful in case one just want to be ready to receive messages on the computer.

You are right, the distro is probavly starting the app while there's still no connection, but this is the default setup here on this distro (kubuntu), I have just installed it yesterday and I haven't customized it at all.

Isn't zapzap trying to connect again as soon as the connection is availble? What does happen if for example someone starts a laptop without being connected and then connects to a wifi in a later stage?

Thank you again!

**Comment by rafatosta** [comment]
> I think that clicking on the icon to launch the program minimized would still be useful in case one just want to be ready to receive messages on the computer.
> 
> You are right, the distro is probavly starting the app while there's still no connection, but this is the default setup here on this distro (kubuntu), I have just installed it yesterday and I haven't customized it at all.
> 
> Isn't zapzap trying to connect again as soon as the connection is availble? What does happen if for example someone starts a laptop without being connected and then connects to a wifi in a later stage?
> 
> Thank you again!

He doesn't try to reconnect. It's an old demand that I always forget. 

I'll try to do that this week!

**Comment by wokawoka** [comment]
> > I think that clicking on the icon to launch the program minimized would still be useful in case one just want to be ready to receive messages on the computer.
> > You are right, the distro is probavly starting the app while there's still no connection, but this is the default setup here on this distro (kubuntu), I have just installed it yesterday and I haven't customized it at all.
> > Isn't zapzap trying to connect again as soon as the connection is availble? What does happen if for example someone starts a laptop without being connected and then connects to a wifi in a later stage?
> > Thank you again!
> 
> He doesn't try to reconnect. It's an old demand that I always forget.
> 
> I'll try to do that this week!

It would be great.
Thank you

**Comment by rafatosta** [comment]
> > > I think that clicking on the icon to launch the program minimized would still be useful in case one just want to be ready to receive messages on the computer.
> > > You are right, the distro is probavly starting the app while there's still no connection, but this is the default setup here on this distro (kubuntu), I have just installed it yesterday and I haven't customized it at all.
> > > Isn't zapzap trying to connect again as soon as the connection is availble? What does happen if for example someone starts a laptop without being connected and then connects to a wifi in a later stage?
> > > Thank you again!
> > 
> > 
> > He doesn't try to reconnect. It's an old demand that I always forget.
> > I'll try to do that this week!
> 
> It would be great. Thank you

Please open a new issue about this. That way I won't forget 😅🤣

**Comment by wokawoka** [comment]
but is there a chance to implement a "start in tray" feature different from the "start with the system" one ?
If so, should we re-open this issue?

**Comment by rafatosta** [comment]
> but is there a chance to implement a "start in tray" feature different from the "start with the system" one ? If so, should we re-open this issue?

No. I will implement an "always start minimized" option

**Comment by wokawoka** [comment]
It would be very useful. Thank you
