### ISSUE TITLE
Tray icon with unread messages bug

### ISSUE THREAD

**Issue by mcdemon05** [rafatosta/zapzap#175]
Sometimes tray icon shows that have unread message
![image](https://github.com/rafatosta/zapzap/assets/15751984/8d99e757-f15e-4f4c-adf7-72594eb0cb83)
but there aren't unread messages

How I can debug this?

FEDORA 38 GNOME

**Comment by mcdemon05** [comment]
I use ZapZap with 2 users.

**Comment by rafatosta** [comment]
> I use ZapZap with 2 users.

With multiple users, the counter sums all existing notifications. Surely one of your users has one.

**Comment by rafatosta** [comment]
> I use ZapZap with 2 users.

With multiple users, the counter sums all existing notifications. Surely one of your users has one.

**Comment by mcdemon05** [comment]
I tell you for sure.
There are no unread messages on both users.
But the icon can show supposedly there is one.

Then if someone writes to the user, the tray icon will still show 1 message. And if I read it, the icon will already be updated and will show that there are no messages.
But until no one has written, the icon may hang for a long time, that supposedly there is a message that does not exist.
