### ISSUE TITLE
Disable notifications in Users management

### ISSUE THREAD

**Issue by mcdemon05** [rafatosta/zapzap#176]
In the current version of the program, I can disable an additional account, and I use this in order not to receive notifications from my work account during non-working hours.
But I would like not to disable the account, but only disable notifications on the account. Ideally, specify the schedule on which days and hours to turn off notifications automatically.

**Comment by mcdemon05** [comment]
Thanks for the update.
But now, if I uncheck the notifications box on the second account, when a message arrives on the second account, the tray icon still shows the presence of new messages.
Is it possible to disable the indication of new messages in the tray when the checkbox is unchecked?

**Comment by rafatosta** [comment]
> Thanks for the update.
> But now, if I uncheck the notifications box on the second account, when a message arrives on the second account, the tray icon still shows the presence of new messages.
> Is it possible to disable the indication of new messages in the tray when the checkbox is unchecked?

I totally forgot about the notification counter 🤣😅
It makes sense to disable the counter. I'll fix it and release an update soon
