### ISSUE TITLE
Weird app border in Fedora 38 with Gnome

### ISSUE THREAD

**Issue by gremo** [rafatosta/zapzap#183]
Hello, thank you for your great app.

It seems to work just fine. I've just a small problem with the window bordering, they looks so weir. Do you know what the issue could be?

![2023-09-26_20-14](https://github.com/rafatosta/zapzap/assets/1532616/52347d84-04e7-4a1b-ba07-594709d39082)

```txt
NAME="Fedora Linux"
VERSION="38 (Thirty Eight)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Thirty Eight)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
```

**Comment by gremo** [comment]
Sorry found it the option "Window" was un-ticked.

**Comment by rafatosta** [comment]
I also use the F38 and it doesn't look like that. The decor is a little dark in Wayland, but not like that.

**Comment by gremo** [comment]
@rafatosta thanks problem resolved,  don't know why the option "Window" was disabled, my bad.

**Comment by rafatosta** [comment]
I have shown by default there are some updates because of some Wayland problems and QT. It works perfectly and I use it here, but some lay users may think it's system bug.So I left it to enable you at risk

**Comment by tywil04** [comment]
> Sorry found it the option "Window" was un-ticked.

I have this exact same issue but I don't understand what you mean by this
