### ISSUE TITLE
Zapzap shows errors when executing from the console.

### ISSUE THREAD

**Issue by saltasatelites** [rafatosta/zapzap#186]
As nativefier is an abandoned project, I've started to find another whatsapp client and this one looks very clean and light. When I start the application from my console appears these messages related with instances although Zapzap works without any problem.
Here they are:
`[juan@Archlinux ~]$ zapzap`
`doh set to ""  --  SystemOnly`
`qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile`
`js: Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.`
`js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.`
`js: Error with Permissions-Policy header: Unrecognized feature: 'payment'.`
`js: Error with Permissions-Policy header: Unrecognized feature: 'usb'.`

This is all the info that I'm able to give to you, but if you know another way to debug, please tell me and I will do it to send a report.
Running on Arch Linux + Sway (not sure whether it's important or not))

Greetings

**Comment by rafatosta** [comment]
Hello, these errors do not affect the functioning of the problem. I'm checking to make sure it doesn't appear in the terminal so as not to make a bad impression.

Are you using via AUR?

**Comment by saltasatelites** [comment]
Thanks for your answer. Yes, via AUR, but without using any AUR helper.

**Comment by rafatosta** [comment]
> Thanks for your answer. Yes, via AUR, but without using any AUR helper.

The AUR package is not maintained by me and I do not recommend using it. There are annoying bugs and strange behaviors and to this day I still don't understand why.
But about the errors you mentioned earlier, there is nothing to worry about. These are just warnings!
