### ISSUE TITLE
Wayland has incorrect window decorations

### ISSUE THREAD

**Issue by tywil04** [rafatosta/zapzap#187]
![incorrect window decorations (ignore highlight)](https://github.com/rafatosta/zapzap/assets/68185249/9613e390-4a69-414c-ae3c-742d9c54874f)

The picture shows the incorrect window decorations (ignore the highlight).

I can use the correct window decorations when I disable access to wayland. This is a workaround because I feel like wayland should just work out of the box.

**Comment by rafatosta** [comment]
The system decoration in wayland works correctly here on the f38. Anyway, there are two options: use x11 or use the app's own decoration, which is available in the settings menu

**Comment by tywil04** [comment]
How do you use the apps own decorations? I don't see a setting for it. 

And do the apps own decorations differ from my screenshot?

**Comment by rafatosta** [comment]
> How do you use the apps own decorations? I don't see a setting for it. 
> 
> And do the apps own decorations differ from my screenshot?
Look:
https://raw.githubusercontent.com/rafatosta/zapzap/main/share/screenshot/system.png

**Comment by rafatosta** [comment]
> How do you use the apps own decorations? I don't see a setting for it. 
> 
> And do the apps own decorations differ from my screenshot?
Look:
https://raw.githubusercontent.com/rafatosta/zapzap/main/share/screenshot/system.png

**Comment by tywil04** [comment]
Oh, its not working correctly then. When I have disabled wayland and use x11, I dont have the menu button in the top bar, so I cannot access that screen

**Comment by rafatosta** [comment]
> Oh, its not working correctly then. When I have disabled wayland and use x11, I dont have the menu button in the top bar, so I cannot access that screen

Use the menu bar!

**Comment by tywil04** [comment]
There is no menu bar either

**Comment by rafatosta** [comment]
> Wayland socket disabled: ![image](https://user-images.githubusercontent.com/68185249/276029276-57f115e3-c285-42ee-a9dc-9e824a61b1a2.png)
> 
> Wayland socket enabled: ![image](https://user-images.githubusercontent.com/68185249/276029489-9e86acc2-b040-4927-acce-33c5384e1421.png)
> 
> As you can see, no menu bar or hamburger menu button

There is no reason why you disabled it!!!
Enable it with ctrl+ m and access the settings

**Comment by tywil04** [comment]
That worked but I never disabled the menu bar, it was like that by default. The setting is even unchecked once I open the menu.
