### ISSUE TITLE
Crashes when try to save a file (KDE 6)

### ISSUE THREAD

**Issue by Tahinli** [rafatosta/zapzap#193]
Hi, ZapZap crashes, when I try to save downloaded content to different location via "save as" feature.

I don't know if this helps but, I also have these in my terminal.

<img width="552" alt="image" src="https://github.com/rafatosta/zapzap/assets/96421894/b75397a7-c21c-4d74-b068-a12cc619f789">

**Comment by rafatosta** [comment]
> Hi, ZapZap crashes, when I try to save downloaded content to different location via "save as" feature.
> 
> I don't know if this helps but, I also have these in my terminal.
> 
> <img width="552" alt="image" src="https://github.com/rafatosta/zapzap/assets/96421894/b75397a7-c21c-4d74-b068-a12cc619f789">
> 
> 
> 

Is this file too big? I used this option today and it worked. 
Check in Flatseal if you have permission to save in the directory you want.

**Comment by rafatosta** [comment]
These logs have no relation to the error, they are just WebEngine execution logs.

**Comment by Tahinli** [comment]
> > Hi, ZapZap crashes, when I try to save downloaded content to different location via "save as" feature.
> > I don't know if this helps but, I also have these in my terminal.
> > <img alt="image" width="552" src="https://private-user-images.githubusercontent.com/96421894/331834759-b75397a7-c21c-4d74-b068-a12cc619f789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzM1OTEsIm5iZiI6MTcxNjA3MzI5MSwicGF0aCI6Ii85NjQyMTg5NC8zMzE4MzQ3NTktYjc1Mzk3YTctYzIxYy00ZDc0LWIwNjgtYTEyY2M2MTlmNzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzMDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGYzYzJhZTA5OTBiODBhMDk5ZjQ2YzZmMjZhYjAyZDg4OTMzY2IyNmIwODQ5NzU5MDUzMjAzZDNlMWE4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3oIY2BZ0sQ6lhH5UFWf1cjaaQBF8o2Y3bflgQbuVSKU">
> 
> Is this file too big? I used this option today and it worked. Check in Flatseal if you have permission to save in the directory you want.

It doesn't even asking me directory. I tried with both 27mb and 2mb it crashes for both.

**Comment by Deadite** [comment]
I'm having the same problem when clicking + attach file (or dragging an attachment into the chat window),  Using openSUSE Tumbleweed w/ Plasma 6.0.4.  Happens on both the flatpak version and the build in the openSUSE repository.  The application just exits.

[redacted]@[redacted]:~> zapzap
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries'
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
js: Error with Permissions-Policy header: Unrecognized feature: 'battery'.
js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries'
Segmentation fault (core dumped) [<- after clicking attach video]

I was unable to locate any log or dump file to help.

**Comment by rafatosta** [comment]
> > > Hi, ZapZap crashes, when I try to save downloaded content to different location via "save as" feature.
> > > I don't know if this helps but, I also have these in my terminal.
> > > <img alt="image" width="552" src="https://private-user-images.githubusercontent.com/96421894/331834759-b75397a7-c21c-4d74-b068-a12cc619f789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzM1OTEsIm5iZiI6MTcxNjA3MzI5MSwicGF0aCI6Ii85NjQyMTg5NC8zMzE4MzQ3NTktYjc1Mzk3YTctYzIxYy00ZDc0LWIwNjgtYTEyY2M2MTlmNzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzMDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGYzYzJhZTA5OTBiODBhMDk5ZjQ2YzZmMjZhYjAyZDg4OTMzY2IyNmIwODQ5NzU5MDUzMjAzZDNlMWE4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3oIY2BZ0sQ6lhH5UFWf1cjaaQBF8o2Y3bflgQbuVSKU">
> > 
> > 
> > Is this file too big? I used this option today and it worked. Check in Flatseal if you have permission to save in the directory you want.
> 
> It doesn't even asking me directory. I tried with both 27mb and 2mb it crashes for both.

There is certainly something wrong with your FlatPak installation. Try to reinstall Zapzap

**Comment by rafatosta** [comment]
I tested and there is nothing wrong with dragging files and saving

https://github.com/rafatosta/zapzap/assets/18619894/efcc71bd-c236-430d-af0e-5da5eda63994

**Comment by rafatosta** [comment]
> I'm having the same problem when clicking + attach file (or dragging an attachment into the chat window), Using openSUSE Tumbleweed w/ Plasma 6.0.4. Happens on both the flatpak version and the build in the openSUSE repository. The application just exits.
> 
> [redacted]@[redacted]:~> zapzap Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries' Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries' Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries' qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile QPropertyAnimation: you're trying to animate the non-writable property width of your QObject js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'. js: Error with Permissions-Policy header: Unrecognized feature: 'battery'. js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'. js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'. Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries' Segmentation fault (core dumped) [<- after clicking attach video]
> 
> I was unable to locate any log or dump file to help.



> I'm having the same problem when clicking + attach file (or dragging an attachment into the chat window), Using openSUSE Tumbleweed w/ Plasma 6.0.4. Happens on both the flatpak version and the build in the openSUSE repository. The application just exits.
> 
> [redacted]@[redacted]:~> zapzap Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries' Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries' Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries' qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile QPropertyAnimation: you're trying to animate the non-writable property width of your QObject js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'. js: Error with Permissions-Policy header: Unrecognized feature: 'battery'. js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'. js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'. js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'. Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries' Segmentation fault (core dumped) [<- after clicking attach video]
> 
> I was unable to locate any log or dump file to help.

First, the OpenSuse Repository package is not kept by me, so I do not recommend its use.

 This error is due to lack of packages for the spelling broker and so it will not work.
`Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'`

It is difficult to support if the user does not use the official means. The Aur is all bugged and users still insist on it instead of Flatpak ... I don't understand.

**Comment by rafatosta** [comment]
Build Zapzap in Appimage, can test and check if the error continues?
https://github.com/rafatosta/zapzap/releases/latest

**Comment by rafatosta** [comment]
Is this the OpenSuse repository?
https://build.opensuse.org/package/show/openSUSE:Factory/zapzap

If so, it's outdated !!
![image](https://github.com/rafatosta/zapzap/assets/18619894/25f8abd1-b799-4def-a9a1-170b42dcb428)

**Comment by Tahinli** [comment]
I tried to reinstall via flatpak but still crashes

**Comment by Tahinli** [comment]
https://github.com/rafatosta/zapzap/assets/96421894/88953b5c-a023-4b1c-897e-09db0f0da310

**Comment by rafatosta** [comment]
> 
> https://github.com/rafatosta/zapzap/assets/96421894/88953b5c-a023-4b1c-897e-09db0f0da310
> 
> 

Which distro? Are you using tilling? Disable and test

**Comment by rafatosta** [comment]
And set zapzap to x11 on Flatseal

**Comment by Tahinli** [comment]
Fedora 40, KDE Plasma 6
![image](https://github.com/rafatosta/zapzap/assets/96421894/22d1fc0c-9704-41e9-93f2-9fcf1397ca41)
I also tried with disabling wayland. Still exists.

Problem also consists in fullscreen

**Comment by rafatosta** [comment]
> Fedora 40, KDE Plasma 6
> ![image](https://github.com/rafatosta/zapzap/assets/96421894/22d1fc0c-9704-41e9-93f2-9fcf1397ca41)
> I also tried with disabling wayland. Still exists.
> 
> Problem also consists in fullscreen

I'm going to create a VM with Fedora KDE to test... just a moment

**Comment by rafatosta** [comment]
> Fedora 40, KDE Plasma 6
> ![image](https://github.com/rafatosta/zapzap/assets/96421894/22d1fc0c-9704-41e9-93f2-9fcf1397ca41)
> I also tried with disabling wayland. Still exists.
> 
> Problem also consists in fullscreen

Have you tried using Copr?

**Comment by Tahinli** [comment]
> > Fedora 40, KDE Plasma 6
> > ![image](https://private-user-images.githubusercontent.com/96421894/331869152-22d1fc0c-9704-41e9-93f2-9fcf1397ca41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjMzMzcsIm5iZiI6MTcxNjEyMzAzNywicGF0aCI6Ii85NjQyMTg5NC8zMzE4NjkxNTItMjJkMWZjMGMtOTcwNC00MWU5LTkzZjItOWZjZjEzOTdjYTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyNTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MWE2MGJmYTQ3Y2IwOTU5MGI2MzI4MmI5NGI2MTEwZjU1MjU5NDU1Mzg0NWE5ZmIyMjU0OWM4M2I1Y2VjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.73DeW1eNRntAquH8nY-aSmQWMc-cDESrPSDqajS10AY)
> > I also tried with disabling wayland. Still exists.
> > Problem also consists in fullscreen
> 
> Have you tried using Copr?

Nope, I ignore copr repos if it's not really necessary.

**Comment by rafatosta** [comment]
I was able to replicate the error in Fedora 40 kde 6.0. I believe some change in KDE 6 + Flatpak is causing the error, because in Fedora Worktation 40 (what I use) this error does not happen.

 However, in Fedora 40 kDE 6.0, the installation is perfectly working via COPR.

 As it does not show any errors at the end makes my clearance difficult. I will try to do this as soon as possible, but it is no guarantee of anything.

**Comment by rafatosta** [comment]
I had some strange reports when Fedora 40 kde 6 was in beta. All of them virtually impossible to debug for not featuring logs.

 Zapzap uses the latest version of the QT and builds the code for file rescue opening according to the documentation.

**Comment by rafatosta** [comment]
The problem is related between KDE 6 and Qt 6.7 and 6.6 and not on Zapzap.

 I am making a Fix for Flatpak (Downgrade to Qt 6.5), but by COPR the problem will continue until KDE 6 and Qt communicate correctly in the part of File Choose because of the fedora repository version.

**Comment by AxeldeWater** [comment]
Is it possible that this problem is already known to KDE/Flatpak Devs and that they are working on it?

**Comment by rafatosta** [comment]
> Is it possible that this problem is already known to KDE/Flatpak Devs and that they are working on it?

I have no idea. Build a minimum example outside of Zapzap and worked correctly.

 However, exactly the same code works in 6.5 and no longer at 6.6 or 6.7 and I have not changed anything in my code and that only happens in KDE. In gnome does not present this error, which makes it difficult to debug.

**Comment by AxeldeWater** [comment]
Are there no logs of KDE errors?

**Comment by AxeldeWater** [comment]
https://unix.stackexchange.com/questions/423870/where-are-the-kde-plasmashell-logs

https://www.reddit.com/r/kde/comments/jvuiu2/where_to_look_for_logs_if_plasma_is_not_working/

Here they say some stuff about journalctl to see logs from KDE. Maybe this will help?

**Comment by rafatosta** [comment]
> https://unix.stackexchange.com/questions/423870/where-are-the-kde-plasmashell-logs
> 
> https://www.reddit.com/r/kde/comments/jvuiu2/where_to_look_for_logs_if_plasma_is_not_working/
> 
> Here they say some stuff about journalctl to see logs from KDE. Maybe this will help?

No errors for me, it just closes. 

I made a simple replica of Zapzap in another repository and filechoose worked. The problem is probably in my application and I will have to do a line-by-line debug.

This problem only occurs on KDE. I use Gnome and there are no failures and this makes it difficult to know what the problem really is.

Maybe I should rebase all the code running on KDE 6 😭

**Comment by AxeldeWater** [comment]
Hmmm... The thing is that your code works, both on earlier versions and on Gnome (and Cinnamon), if it were a bug in your code, i dont think it would work on those other versions. It is much more likely it is a bug introduced in KDE, or maybe dolphin (if I'm correct that is the file manager of KDE), or the runtime...

**Comment by rafatosta** [comment]
> Hmmm... The thing is that your code works, both on earlier versions and on Gnome (and Cinnamon), if it were a bug in your code, i dont think it would work on those other versions. It is much more likely it is a bug introduced in KDE, or maybe dolphin (if I'm correct that is the file manager of KDE), or the runtime... Maybe file a report or search for contact from the KDE or Flatpak Devs?

This is the problem, I can't reproduce outside my app!

 It only happens within Zapzap and does not generate any exception that can be analyzed. I am assuming that there is something in the Zapzap code, because it is not a simple code and I have evolved over these two years.

**Comment by AxeldeWater** [comment]
How "complete" would you call the 'simple replica' you made compared to the original ZapZap?

**Comment by AxeldeWater** [comment]
What was the problem?

**Comment by rafatosta** [comment]
> What was the problem?

The problem is that in Qt 6.7 is not accepting to style the Qwidget.
`QWidget{
            color: red;
 }
`
 That is, when applying any property, QFileDialog does not open and the app is closed to seek.
 
 I will enjoy and revise Stylization before release the correction
