### ISSUE TITLE
ZapZap stoped to work after latest update

### ISSUE THREAD

**Issue by jannotti-glaucio** [rafatosta/zapzap#195]
I installed the latest update today (2024/05/21) and after that the app doesn`t not work more.
I`m using in on Linux Mint 21.3 Cinnamon, kernel 6.5.0, Flatpack 1.12.7

**Comment by rafatosta** [comment]
> I installed the latest update today (2024/05/21) and after that the app doesn`t not work more.
> I`m using in on Linux Mint 21.3 Cinnamon, kernel 6.5.0, Flatpack 1.12.7

Please run via terminal and post the output.
`flatpak run com.rtosta.zapzap`

**Comment by jannotti-glaucio** [comment]
[~]$ flatpak run com.rtosta.zapzap
error: runtime/org.kde.Platform/x86_64/6.5 not installed

**Comment by rafatosta** [comment]
This is something related to Flatpak and not to Zapzap.

 Try
`flatpak update`

 Or install manually

`flatpak install flathub org.kde.Platform//6.5 org.kde.Sdk//6.5 com.riverbankcomputing.PyQt.BaseApp//6.5 `

**Comment by jannotti-glaucio** [comment]
It worked! Thanks

**Comment by AxeldeWater** [comment]
@rafatosta Did you move ZapZap to the 6.5 runtime instead of the 6.7 runtime?

**Comment by rafatosta** [comment]
> @rafatosta Did you move ZapZap to the 6.5 runtime instead of the 6.7 runtime?

Why is there a problem with KDE6 when saving and sending files via filechoose.

I'm trying to solve this problem and since version 6.5 works, I decided to downgrade temporarily.

**Comment by AxeldeWater** [comment]
Ah, that's understandable! Take your time!
