### ISSUE TITLE
There is no option to change fonts, it becomes an issue for other languages

### ISSUE THREAD

**Issue by RafayAhmad7548** [rafatosta/zapzap#198]
i would really appreciate adding an option to select font to be used to display the text, i am facing issues rendering urdu font, i have the fonts installed on my system but can't use them in zapzap

**Comment by rafatosta** [comment]
> i would really appreciate adding an option to select font to be used to display the text, i am facing issues rendering urdu font, i have the fonts installed on my system but can't use them in zapzap

What's your language? What problem are you having, is it not visible because of the rendering or is it too small?

**Comment by RafayAhmad7548** [comment]
Language is Urdu 
The default font is very hard to read
I have other fonts but don't know how to use them here

**Comment by rafatosta** [comment]
@RafayAhmad7548 
Please uninstall what you have and install from this file. See if it improved the source.
 
https://github.com/rafatosta/zapzap/releases/download/5.3.5/zapzap.flatpak

The installation is the same, but pointing to the file:
`flatpak install ~/zapzap.flatpak`

**Comment by rafatosta** [comment]
> I am currently using aur version Anything wrong with it? I guess i will give flarpak a try

The AUR is not maintained by me and is not a stability parameter, it is full of problems. 

Test the official versions and see if the problem occurs and report it here.

**Comment by RafayAhmad7548** [comment]
Ok thanks, i will test and report back

**Comment by AxeldeWater** [comment]
@RafayAhmad7548 Any results?

**Comment by RafayAhmad7548** [comment]
Sorry for my late reply,
The fonts were readable in the flatpak version
Thank you
