### ISSUE TITLE
Congelamento de vídeos

### ISSUE THREAD

**Issue by caiocn** [rafatosta/zapzap#20]
Videos reproduzidos dentro do whats ficam congelando.
Utilizo placa AMD

**Comment by rafatosta** [comment]
Olá, Caio.
Aqui está normal. Poderia fornecer mais detalhes sobre o seu hardware e ambiente execução (KDE, Gnome, Wayland, X11, etc)?

**Comment by caiocn** [comment]
Fedora 35 com Gnome

SISTEMA DE JANELAS: x11
CPU: Intel® Xeon(R) CPU E5-2650 v2 @ 2.60GHz × 16 
RAM: 64gb
GPU: AMD® Radeon rx 580 series
SSD

**Comment by rafatosta** [comment]
Muito estranho. Com esse hardware não era para acontecer isso. 
Não há muito o que eu possa fazer se não consigo reproduzir aqui 🫤
