### ISSUE TITLE
It is not openning

### ISSUE THREAD

**Issue by JumperLuko** [rafatosta/zapzap#200]
Previously there were problems on my laptop with the app freezing and not opening, now it happens on my PC that it crashes when opening.

Fedora 40
Flatpak 1.15.8
6.8.10-300.fc40.x86_64

$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zapzap --file-forwarding com.rtosta.zapzap @@u %u @@
[3:25:0603/140358.214676:FATAL:flatpak_sandbox.cc(289)] Your Flatpak installation is setuid, which is not supported

![image](https://github.com/rafatosta/zapzap/assets/22037309/ea2f9173-f071-4420-9447-29877923887e)

**Comment by rafatosta** [comment]
Are you using this command to open Zapzap?
`$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zapzap --file-forwarding com.rtosta.zapzap @https://github.com/U %u`

Do you have nvidia?

Have you tried to install Zapzap via COPR and check if the error also occurs?

**Comment by JumperLuko** [comment]
AMD here.

``` BASH
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zapzap --file-forwarding com.rtosta.zapzap @https://github.com/U %u
[3:25:0603/181517.929672:FATAL:flatpak_sandbox.cc(289)] Your Flatpak installation is setuid, which is not supported

```

Is COPR the fedora repository? I tried to install it from the flathub repository, but I get this error.

**Comment by rafatosta** [comment]
> AMD here.
> 
> ``` BASH
> $ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zapzap --file-forwarding com.rtosta.zapzap @https://github.com/U %u
> [3:25:0603/181517.929672:FATAL:flatpak_sandbox.cc(289)] Your Flatpak installation is setuid, which is not supported
> 
> ```
> 
> Is COPR the fedora repository? I tried to install it from the flathub repository, but I get this error.

https://copr.fedorainfracloud.org/coprs/rafatosta/zapzap/
