### ISSUE TITLE
No icon appears in system tray in Xubuntu

### ISSUE THREAD

**Issue by xgrind** [rafatosta/zapzap#203]
O ícone na bandeja do sistema parou de funcionar nas versões recentes do Zazap.
Utilizo Xubuntu 22.04

![Captura de tela_2024-06-06_19-49-19](https://github.com/rafatosta/zapzap/assets/3290706/727afe48-c007-4f32-8684-5a988cb321a2)

**Comment by rafatosta** [comment]
> O ícone na bandeja do sistema parou de funcionar nas versões recentes do Zazap.
> Utilizo Xubuntu 22.04
> 
> ![Captura de tela_2024-06-06_19-49-19](https://github.com/rafatosta/zapzap/assets/3290706/727afe48-c007-4f32-8684-5a988cb321a2)
> 

Está executando sob Wayland ou X11? 

Tente mudar pelo Flatseal e veja se continua, por favor.

**Comment by xgrind** [comment]
Usa X11 e já está ativado no Flatseal

![Captura de tela_2024-06-07_13-38-50](https://github.com/rafatosta/zapzap/assets/3290706/595c5c74-80ee-41ee-8150-8c21fd450faf)

Não sei se te ajuda, mas abrindo o ZapZap pelo terminal, recebo esse log:

> michael_martins@ARQ-TI03:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zapzap --file-forwarding com.rtosta.zapzap @@u %u @@
Qt: Session management error: Could not open network socket
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
js: Error with Permissions-Policy header: Unrecognized feature: 'battery'.
js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.
js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
js: Error with Permissions-Policy header: Unrecognized feature: 'battery'.
js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.

**Comment by rafatosta** [comment]
> Usa X11 e já está ativado no Flatseal
> 
> ![Captura de tela_2024-06-07_13-38-50](https://github.com/rafatosta/zapzap/assets/3290706/595c5c74-80ee-41ee-8150-8c21fd450faf)
> 
> Não sei se te ajuda, mas abrindo o ZapZap pelo terminal, recebo esse log:
> 
> > michael_martins@ARQ-TI03:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zapzap --file-forwarding com.rtosta.zapzap @@u %u @@
> Qt: Session management error: Could not open network socket
> qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
> QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
> js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
> js: Error with Permissions-Policy header: Unrecognized feature: 'battery'.
> js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
> js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.
> js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
> js: Error with Permissions-Policy header: Unrecognized feature: 'battery'.
> js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
> js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.
> 
> 

Para usar o x11 você precisa **desativar** o Wayland

**Comment by xgrind** [comment]
Fiz um teste com o Lubuntu e apareceu o ícone. Testei com o Mageia Xfce e também apareceu, mas no Xubuntu não aparece. Deve ser bug no plugin do Xubuntu

**Comment by rafatosta** [comment]
> Fiz um teste com o Lubuntu e apareceu o ícone. Testei com o Mageia Xfce e também apareceu, mas no Xubuntu não aparece. Deve ser bug no plugin do Xubuntu
> 

Infelizmente a falta de "padronização" de algumas distros faz com que o funcionamento do app seja comprometido. Pior é quando o usuário altera tando seu sistema que acaba quebrando o app por remover alguns desses padrões.

**Comment by lvf23** [comment]
I think I found the problem, It was the Session D-Bus, after enabling it in Flatseal, the icon appears in system tray icon in Xubuntu 22.04:

<img width="967" height="352" alt="Image" src="https://github.com/user-attachments/assets/7f294f21-751a-4b0f-9ea3-787e3435ba6a" />

Enabling it, here is the icon appearing:

<img width="400" height="38" alt="Image" src="https://github.com/user-attachments/assets/6088ae82-ebd1-4bbd-bc66-021b807cc066" />
