### ISSUE TITLE
GNOME 43.9 INTERFACE ERROR

### ISSUE THREAD

**Issue by jas-ells** [rafatosta/zapzap#206]
Hello! I have been using Zapzap for some time now. I think it is the best for Linux. However, with the new updates, the integration with the GNOME 43.9 interface has not improved. With the new update, the interface is shaky, causing bugs, freezing, among other things. Unfortunately, I was forced to uninstall it, since I was unable to disable the integration with the GNOME system. I hope to return in the future when this problem is fixed. 

Install via Flatpak from the Debian app store.

Acer Aspire 5 Notebook
Debian 12.5 stable
GNOME 43.9

**Comment by rafatosta** [comment]
> Hello! I have been using Zapzap for some time now. I think it is the best for Linux. However, with the new updates, the integration with the GNOME 43.9 interface has not improved. With the new update, the interface is shaky, causing bugs, freezing, among other things. Unfortunately, I was forced to uninstall it, since I was unable to disable the integration with the GNOME system. I hope to return in the future when this problem is fixed.
> 
> Install via Flatpak from the Debian app store.
> 
> Acer Aspire 5 Notebook Debian 12.5 stable GNOME 43.9

Which integration are you referring to?
Does it have NVidia, does it run on Wayland or X11? Provide more details, please.
