### ISSUE TITLE
Bug loading ZapZap homepage — flatpak version

### ISSUE THREAD

**Issue by DavyRetroGamer** [rafatosta/zapzap#207]
Hello, Rafael, guys! 👍😁👍

I'm having a problem with my ZapZap flatpak version that I've been experiencing for a few days now. The issue is these: homepage doesn't load, QR code doesn't load, nothing loads! The page goes dark, and when I press F5, everything turns white and doesn't load anything; But I can change the options on the page. What will it be? What's the matter?

NOTE: I've already uninstalled, installed again, installed and uninstalled through the store and the terminal as well, I've already restarted my PC and nothing!

My distro: BigLinux — Kernel 68.
My drivers: NVIDIA.
Mode: X11.

Thank you for your attention, and I hope you understand me! 👍😁👍

**Comment by rafatosta** [comment]
I have no idea!

**Comment by DavyRetroGamer** [comment]
Hello, Rafael! 👍😁👍

Leave it alone, I've got it figured out! Now everything is working perfectly! 👍😁👍
