### ISSUE TITLE
downloading pictures / videos is not possible in OpenSuse Aeon

### ISSUE THREAD

**Issue by TheRsKing** [rafatosta/zapzap#208]
![grafik](https://github.com/rafatosta/zapzap/assets/130909958/3b7215d1-2684-4e29-b18c-312218aaab79)
if you want to download a media via this toolbar, nothing happens

this message appears in the logs:
'qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::zwp_text_input_v3_leave(wl_surface*) Got leave event for surface 0x0 focused surface 0x562e3699e710'

**Comment by rafatosta** [comment]
It's working here.

[Gravação de tela de 2024-06-24 17-01-04.webm](https://github.com/rafatosta/zapzap/assets/18619894/25a2b02e-8e91-4ea7-8692-137eeb295c12)

**What is your distro?**

**Comment by TheRsKing** [comment]
Hey thanks for the answer
[opensuse Aeon](https://aeondesktop.org) but Zapzap installed via the flatpak

**Comment by TheRsKing** [comment]
short off topic question, just wanted to see if maybe permissions are missing, why does zapzap need access to all host files

**Comment by rafatosta** [comment]
> short off topic question, just wanted to see if maybe permissions are missing, why does zapzap need access to all host files

No. All necessary permissions are activated!
 You can check in flatseal.

**Comment by rafatosta** [comment]
> Hey thanks for the answer [opensuse Aeon](https://aeondesktop.org) but Zapzap installed via the flatpak

![image](https://github.com/rafatosta/zapzap/assets/18619894/c3eadd37-128e-4577-b45d-44d7ebb508ce)

What is the need to use a distro in testing phase?
 There are distro with the same purpose already released and tested.
 I am downloading to test in a VM, but I believe something is missing from the disro side.

**Comment by rafatosta** [comment]
Isn't there an ISO file for quick VM installation?

**Comment by TheRsKing** [comment]
> > Hey thanks for the answer [opensuse Aeon](https://aeondesktop.org) but Zapzap installed via the flatpak
> 
> 
> 
> ![image](https://github.com/rafatosta/zapzap/assets/18619894/c3eadd37-128e-4577-b45d-44d7ebb508ce)
> 
> 
> 
> What is the need to use a distro in testing phase?
> 
>  There are distro with the same purpose already released and tested.
> 
>  I am downloading to test in a VM, but I believe something is missing from the disro side.

Although it is in testing, it is the most stable distro I have ever tested. The testing is only there because fde is still pending for the full release. I like it much more then silverblue etc..

**Comment by TheRsKing** [comment]
> Isn't there an ISO file for quick VM installation?

Not an iso but since it uses an image based installation you can skip the installer and unzip and use this file (tested and works in gnome boxes): http://download.opensuse.org/tumbleweed/appliances/tik-osimage-openSUSE-Aeon.x86_64.raw.xz

**Comment by TheRsKing** [comment]
> Isn't there an ISO file for quick VM installation?

I doubt that it is a distro problem because the download via right click also works

**Comment by rafatosta** [comment]
> > but I believe something is missing from the disro side.
> 
> I doubt that it is a distro problem because the download via right click works

I will try to reproduce. But if there really is a problem, I won't make any "correction", as there is no problem with my code. What's more, it's a distro that hasn't even been released yet. Therefore, it is not ready for use.

**Comment by TheRsKing** [comment]
Just asked in the Aeon matrix chat. Someone has also tested it (in a vm) and it worked there, so Aeon doesn't seem to be the problem. My new guess for the cause of the problem is fractional scaling. I will test this tonight to see if it is true

**Comment by rafatosta** [comment]
> Just asked in the Aeon matrix chat. Someone has also tested it (in a vm) and it worked there, so Aeon doesn't seem to be the problem. My new guess for the cause of the problem is fractional scaling. I will test this tonight to see if it is true

So it's a problem with your installation and not with Zapzap.

**Comment by TheRsKing** [comment]
okay i have new findings, the problem is independent of aeon (i would have been very surprised). it only occurs when using fractional-scaling in a maximized window. I don't know if zapzap can do anything because it's more of a bug with fractional scaling. thanks for your efforts though
