### ISSUE TITLE
What's the shortcut to show the menu in the flatpak version?

### ISSUE THREAD

**Issue by yasminzy** [rafatosta/zapzap#209]
Hello. I'm using the flatpak version on Linux Mint.

I just want to ask, what's the shortcut to show the menu? I forget about since I've hidden it for a long time. I've tried uninstalling and reinstalling but when I open Zapzap again, I'm already signed in and the old setting is already applied, including the hidden menu.

Thanks in advance.

**Comment by rafatosta** [comment]
> Hello. I'm using the flatpak version on Linux Mint.
> 
> I just want to ask, what's the shortcut to show the menu? I forget about since I've hidden it for a long time. I've tried uninstalling and reinstalling but when I open Zapzap again, I'm already signed in and the old setting is already applied, including the hidden menu.
> 
> Thanks in advance.

Hello. The menu bar is no longer available.
You can access the settings through the tray menu, through the sidebar within the app or through the shortcut ctrl+p

**Comment by rafatosta** [comment]
This option opens the Zapzap settings panel.
![WhatsApp Image 2024-06-24 at 16 50 05](https://github.com/rafatosta/zapzap/assets/18619894/e7dc19c4-60e2-4d13-b9e7-8166cf8e9118)
