### ISSUE TITLE
Zapzap closes by itself

### ISSUE THREAD

**Issue by supertrackster** [rafatosta/zapzap#21]
After the last update on flatpack, Zapzap closes after a few minutes for no reason (I don't know how to quantify the time).

**Comment by rafatosta** [comment]
Did you make any changes to the settings, like restrict in background?

To improve the report I suggest running it via terminal and checking the output when closing alone.

flatpak rum com.rtosta.zapzap

**Comment by supertrackster** [comment]
`[stefano@localhost ~]$ flatpak run com.rtosta.zapzap
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
Qt: Session management error: None of the authentication protocols specified are supported
qt.webenginecontext: 

GLImplementation: desktop
Surface Type: OpenGL
Surface Profile: NoProfile
Surface Version: 3.1
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  application-name ZapZap 
  *  browser-subprocess-path /app/bin/QtWebEngineProcess 
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/zapzap/engine/browser.py", line 97, in show_notification
    n.show()
  File "/app/lib/python3.9/site-packages/zapzap/services/dbus_notify.py", line 110, in show
    nid = DBUS_IFACE.Notify(APP_NAME,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.357 was not provided by any .service files
[stefano@localhost ~]$ 
`

**Comment by rafatosta** [comment]
Problem with permission to access the data directory that temporarily stores contact images. I ask you to disable images in notifications to avoid this error, I will soon release a fix to avoid such problems.

What is the distribution?

**Comment by supertrackster** [comment]
I am using Rocky Os, mate desktop + i3wm.

Il sab 30 apr 2022, 21:19 Rafael Tosta Santos ***@***.***> ha
scritto:

**Comment by rafatosta** [comment]
I believe it has something to do with your distro's dbus. Until I analyze it more deeply, I launched this so that it avoids closing.  1ce265cd15173149d6c74d0a620e5f87c74deee8

**Comment by supertrackster** [comment]
Now seems to be ok

**Comment by cmc302a** [comment]
Started happening to me after update to version 4.0

Attaching command line output:

rlos@xiaomi-air-13:~$ flatpak run com.rtosta.zapzap
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name ZapZap 
  *  browser-subprocess-path /app/bin/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

**Comment by rafatosta** [comment]
There is no error. Check if Flatseal is allowing it to run in the background.

**Comment by cmc302a** [comment]
That seems to have solved it! Permission of background was not allowed in Flatseal. Thanks!
