### ISSUE TITLE
frequent crashes

### ISSUE THREAD

**Issue by chrostino** [rafatosta/zapzap#212]
don't know what made it start happening, but I've been experiencing frequent crashes of the app.  I'm using the flatpak app on Fedora 40 with plasma 6.1 and the new nvidia 555 drivers. everytime the app crashes i get a system notification saying "python3.11" crashed. I don't know if it's some specific action that's causing the crash, at first it was happening when trying to type, now it's happening mostly when opening images. I can try to get a log if I'm told how

**Comment by rafatosta** [comment]
> don't know what made it start happening, but I've been experiencing frequent crashes of the app. I'm using the flatpak app on Fedora 40 with plasma 6.1 and the new nvidia 555 drivers. everytime the app crashes i get a system notification saying "python3.11" crashed. I don't know if it's some specific action that's causing the crash, at first it was happening when trying to type, now it's happening mostly when opening images. I can try to get a log if I'm told how

Does this problem happen in X11?

**Comment by chrostino** [comment]
> Does this problem happen in X11?

forgot to mention it's on wayland

**Comment by rafatosta** [comment]
> > Does this problem happen in X11?
> 
> forgot to mention it's on wayland, I don't use X11

Test on x11 and see if the problem happens, please.

**Comment by chrostino** [comment]
disabling the wayland windowing system from flatseal does seem to solve the problem, after some quick testing it didn't crash once

**Comment by rafatosta** [comment]
> disabling the wayland windowing system from flatseal does seem to solve the problem, after some quick testing it didn't crash once

So the problem is with Nvidia!
There's nothing I can do.

If you want, try the rpm version of Copr.

**Comment by chrostino** [comment]
gotcha, maybe it's something to do with the new 555 drivers
