### ISSUE TITLE
Files couldn't be saved to filesystem

### ISSUE THREAD

**Issue by t08094a** [rafatosta/zapzap#216]
I've installed version 5.3 as flatpak. In that version I'm not able to save files in chats to my local filesystem.
In flatseal I have configured different access settings (grant access):
- all user files (filesystem=home)
- other files
  - ~/Downloads/ZapZap Downloads/
  - xdg-config/kdeglobals:ro
  - xdg-download

The log of the console output prints nothing special while clicking the save button:
```
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
js: Error with Permissions-Policy header: Unrecognized feature: 'battery'.
js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
js: Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.
```

**Comment by rafatosta** [comment]
`Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'`

These outputs are not from the flatpak!!
If they are, there is something seriously wrong with your flatpak installation and I recommend reinstalling.

**Comment by AxeldeWater** [comment]
@t08094a Keep in mind that ZapZap saves downloaded files into a folder called "ZapZap Downloads" inside your downloads folder. You might have overlooked that, but I of course could be wrong.

**Comment by t08094a** [comment]
With version 5.3.6 the problem is solved.
