### ISSUE TITLE
Counter stays at one ("1")

### ISSUE THREAD

**Issue by Christel-Mett** [rafatosta/zapzap#217]
If several messages arrive, the counter stays at one ("1") on both the taskbar icon and the icon in the program window at the top left.
My system is Linux Mint 21.3 Cinnamon and the Zapzap version is 5.3 as Flatpak.

**Comment by WolfganP** [comment]
> If several messages arrive, the counter stays at one ("1") on both the taskbar icon and the icon in the program window at the top left. My system is Linux Mint 21.3 Cinnamon and the Zapzap version is 5.3 as Flatpak.

I think the way it's implemented is to notify how many chats/groups contain unread msgs. Then the app internally shows the unread details for each chat on the left.

**Comment by rafatosta** [comment]
> > If several messages arrive, the counter stays at one ("1") on both the taskbar icon and the icon in the program window at the top left. My system is Linux Mint 21.3 Cinnamon and the Zapzap version is 5.3 as Flatpak.
> 
> I think the way it's implemented is to notify how many chats/groups contain unread msgs. Then the app internally shows the unread details for each chat on the left.

Exactly. I just take the amount sent by WhatsApp Web and I have hurt several times and there is no problem on my side.

 There is certainly a chat without reading or bug on whatsapp web itself. Use the browser and make sure the notification also appears, please.

**Comment by AxeldeWater** [comment]
Same version, same distro, nothing wrong with the counter. It will count the amount of chats with unread messages that have arrived from the moment you open the app.

@rafatosta Just to check, is it meant to count all the chats with unread messages or just the ones that had new unread messages arrive from the moment you open the app? Because currently it works like the latter.

**Comment by rafatosta** [comment]
> Same version, same distro, nothing wrong with the counter. It will count the amount of chats with unread messages that have arrived from the moment you open the app.
> 
> @rafatosta Just to check, is it meant to count all the chats with unread messages or just the ones that had new unread messages arrive from the moment you open the app? Because currently it works like the latter.

I don't know for sure, because I don't modify WhatsApp's default behavior. If Whatsapp changes the counting method, it will be reflected in Zapzap.
