### ISSUE TITLE
Images not saved with extensions hence can't be shared to other apps.

### ISSUE THREAD

**Issue by wathika-eng** [rafatosta/zapzap#218]
I selected save as and only after sometime did I note that the filename extension had been cut e.g filename.jpg to filename

**Comment by rafatosta** [comment]
> I selected save as and only after sometime did I note that the filename extension had been cut e.g filename.jpg to filename

Which DE?

 I took the test here at Gnome and is working perfectly.

**Comment by wathika-eng** [comment]
Gnome 46

See below:

https://github.com/user-attachments/assets/5c463e29-edff-49ef-9ba7-3c262be37465

**Comment by rafatosta** [comment]
> Gnome 46
> 
> See below:
> 
> https://github.com/user-attachments/assets/5c463e29-edff-49ef-9ba7-3c262be37465
> 
> 
> 

This image comes from a link preview and not an image file. In this specific case, you will have to add the extension manually.

**Comment by rafatosta** [comment]
> Gnome 46
> 
> See below:
> 
> https://github.com/user-attachments/assets/5c463e29-edff-49ef-9ba7-3c262be37465
> 
> 
> 

This image comes from a link preview and not an image file. In this specific case, you will have to add the extension manually.
