### ISSUE TITLE
Uso excessivo de processador

### ISSUE THREAD

**Issue by thiagodluz** [rafatosta/zapzap#22]
O aplicativo fica usando mesmo parado uma quantidade absurda de processador.

Estou usando um Fedora 35.

[https://imgur.com/EAMyLKU](url)

**Comment by rafatosta** [comment]
Olá, Thiago. Obrigado por reportar! 
Também sou usuário do Fedora e até hoje não notei esse comportamento estranho. Vou observar mais de perto.
Se fechá-lo e abrir novamente esse comportamento continua?

Uma observação: O aplicativo nunca fica "parado" de fato, pois a verificação de novas mensagem acontecem. Esse app apenas "empacota" o Whatsapp Web dentro de um aplicativo nativo com o acréscimo das funcionalidades de rodar em 2o plano e trayIcon.

**Comment by thiagodluz** [comment]
Sim, tentei abrir e fechar e continuou igual. 

Sobre o parado, quis dizer que eu não estaria fazendo nenhum uso dele, apenas rodando em segundo plano, resolvi relatar pelo grande numero de processos do python e com muito processador.

Se precisar de mais algum detalhe é só pedir.

**Comment by rafatosta** [comment]
Geralmente o consumo aqui é esse:
![image](https://user-images.githubusercontent.com/18619894/165596207-9a55d526-1ac1-4f3f-bc1a-4a9bf1bac30a.png)

Aumenta conforme o uso, mas isso é "culpa" do próprio whatsapp por manter algumas coisas em cache.
