### ISSUE TITLE
BUG: Using 10% CPU & 1GB+ RAM.

### ISSUE THREAD

**Issue by qnxdev** [rafatosta/zapzap#220]
I'm using a 16 core CPU device with PopOS and Gnome. 

The app seems to be using too much resources compared to web PWA. And my laptop heats up.
Is there any fix for this?

The scrolling is slow (or smooth?)

**Comment by rafatosta** [comment]
> I'm using a 16 core CPU device with PopOS and Gnome. 
> 
> The app seems to be using too much resources compared to web PWA. And my laptop heats up.
> Is there any fix for this?
> 
> The scrolling is slow (or smooth?)

This sometimes happens because of the synchronization of messages. It has no relation to Zapzap. If you use WhatsApp Web this will also happen, as it is related to your usage and the amount of information you have that needs to be synchronized. 
Don't worry, it will return to normal.

**Comment by qnxdev** [comment]
Well that was not the case. I tried same with whatsapp web PWA, it was using about 500MB RAM, never spiked CPU, fans normal..

Zapzap can't cache messages?

**Comment by rafatosta** [comment]
> Well that was not the case. I tried same with whatsapp web PWA, it was using about 500MB RAM, never spiked CPU, fans normal..
> 
> Zapzap can't cache messages?

Yes, Zapzap stores in cache. However, depending on its use and the amount of messages may take a little longer.

 My use is basically this one below. Only if you enter a new account consumption increases, but after a low time.
![image](https://github.com/user-attachments/assets/132a59b3-4011-42e5-92a6-9ac35821fb81)
