### ISSUE TITLE
Fecha ao salvar

### ISSUE THREAD

**Issue by elppans** [rafatosta/zapzap#221]
Salve, tudo bem?

Aplicativo fecha completamente ao tentar salvar um anexo, qualquer um. Seja imagens, documentos, etc. e não salva o arquivo.
Ao clicar em "Abrir", ele abre normalmente e ao acessar o diretório "ZapZap Downloads", o arquivo está lá.
Tem algum comando pra depurar ou já pegou este erro?
É aplicação em Flatpak

**Comment by rafatosta** [comment]
> Salve, tudo bem?
> 
> Aplicativo fecha completamente ao tentar salvar um anexo, qualquer um. Seja imagens, documentos, etc. e não salva o arquivo.
> Ao clicar em "Abrir", ele abre normalmente e ao acessar o diretório "ZapZap Downloads", o arquivo está lá.
> Tem algum comando pra depurar ou já pegou este erro?
> É aplicação em Flatpak

Tudo bem e você? 

Aqui tem funcionando bem. 

Tá usando qual distro?

**Comment by elppans** [comment]
Salve, desculpe a demora.
No momento estou usando BIG/Manjaro, aplicativo em flatpak.
Era só pra saber mesmo, o resto me virava.

Mas já foi corrigido, atualizei/reinstalei o aplicativo e testei


![image](https://github.com/user-attachments/assets/6221b59a-9825-4ae3-a415-376525f8e503)
