### ISSUE TITLE
Repositório do Mageia no Copr

### ISSUE THREAD

**Issue by xgrind** [rafatosta/zapzap#222]
Boa noite.
Será que consegue criar repositório para o Mageia no Copr? Ou fica muito complicado?
Mageia tem suporte ao copr, mas não dá pra usar o repositório do Fedora.

https://wiki.mageia.org/en/Fedora_COPR

**Comment by rafatosta** [comment]
> Boa noite.
> Será que consegue criar repositório para o Mageia no Copr? Ou fica muito complicado?
> Mageia tem suporte ao copr, mas não dá pra usar o repositório do Fedora.
> 
> https://wiki.mageia.org/en/Fedora_COPR

Boa noite. Se o arquivo de construção for compatível, darei suporte sem problema. 
Vou olhar com calma amanhã.

**Comment by rafatosta** [comment]
@xgrind 

habilitei a constuição para o Mageia 9 no Copr.
Testa ai, por falor. 
https://copr.fedorainfracloud.org/coprs/rafatosta/zapzap/

![image](https://github.com/user-attachments/assets/74c91431-d77e-4274-a513-12998df24ce7)

**Comment by rafatosta** [comment]
Deu problema nas dependências apra o Mageia.
`No matching package to install: 'python3-pyqt6'`

Não encontrou esse pacote para o Mageia. Estou tentando baixar a distro, mas está muito lento o download.

Se você puder pesquisar por 'python3-pyqt6' e verificar se existe, agradeço.

**Comment by xgrind** [comment]
Não tem essa dependência. Estava tentando empacotar ontem

**Comment by xgrind** [comment]
Pra você não precisar baixar instalar o Mageia, pode pesquisar os pacotes por aqui: https://madb.mageia.org/package/list/t_search/whatsapp/application/0/arch/x86_64

**Comment by xgrind** [comment]
Vou pedir para empacotarem. Mas obrigado.

**Comment by rafatosta** [comment]
@xgrind 
Não esqueçe das outras dependências:

- python3-pyqt6
- python3-pyqt6-base
- python3-pyqt6-sip
- python3-pyqt6-webengine

Quando empacotarem, sinalize que faço a construção.
Abraços

**Comment by xgrind** [comment]
Já existem os pacotes no repositório, mas com outros nomes.
Criei o spec. Só subir para o copr e buildar: https://pastebin.com/VrbZUGdC
Já fiz um teste aqui no meu. Compilou e instalou certinho.

**Comment by rafatosta** [comment]
> Já existem os pacotes no repositório, mas com outros nomes.
> Criei o spec. Só subir para o copr e buildar: https://pastebin.com/VrbZUGdC
> Já fiz um teste aqui no meu. Compilou e instalou certinho.
> Talvez não sejam esses pacotes, porque puxou muitas dependências. 
> Se eu conseguir enxugar o pacote, atualizo e te aviso.

Essas "muitas dependências" com certeza é o Qt6, correto? 

Enfim, vou fazer a construção hoje. Valeu!

**Comment by rafatosta** [comment]
@xgrind 

Tudo ok com a contrução. Testa por favor
![image](https://github.com/user-attachments/assets/040a931a-fc5b-4e67-9fad-51d1dafcc99f)

**Comment by xgrind** [comment]
Perfeito. Abriu certinho aqui.
![Captura de tela_2024-07-23_17-32-27](https://github.com/user-attachments/assets/d74f6644-3a4a-4f47-987e-e193f9d056cd)

**Comment by rafatosta** [comment]
> Perfeito. Abriu certinho aqui. ![Captura de tela_2024-07-23_17-32-27](https://private-user-images.githubusercontent.com/3290706/351483409-d74f6644-3a4a-4f47-987e-e193f9d056cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjcwOTAsIm5iZiI6MTcyMTc2Njc5MCwicGF0aCI6Ii8zMjkwNzA2LzM1MTQ4MzQwOS1kNzRmNjY0NC0zYTRhLTRmNDctOTg3ZS1lMTkzZjlkMDU2Y2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMjAzMzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGEwY2I0NmEyMGFlOWVjYTk0NTk4OTI3YjdjNWZiZGJjNGZiYTk2MDlkZmQ2MzgzYjY5MTgwNTAwZmVmZWNhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DtDtnGnPfXJkijUkM98h3ut5e8yTJydlwzEKKqK6DJg)

Ótimo. Já estava criando uma VM para testar.

Qualquer coisa é só avisa!
