### ISSUE TITLE
AppImage or DEB package?

### ISSUE THREAD

**Issue by iamstonecutter** [rafatosta/zapzap#223]
On Arch Linux, someone was awesome enough to package this awesome software into the AUR.

For those of us using Debian and who refuse to run Flatpak, this is a difficult software to install.

Can we please get an AppImage or at least a .DEB package?

**Comment by rafatosta** [comment]
There is an Appimage, but it doesn't have all the features like the spell checker. 

Why not install flatpak? I can not understand

**Comment by rafatosta** [comment]
@iamstonecutter If you do:
`chmod +x build.sh`
`./build.sh 5.3.6`
Will build the AppImage.

I will no longer build AppImage as the functionality is incomplete and my support is limited due to the format.

**Comment by rafatosta** [comment]
> @rafatosta
> 
> Fair enough. Any chance you would provide a pre-compiled tarball for users?

I've already thought about doing it for installation and removal, similar to building the AppImage. But I'm out of time at the moment.
Your contribution is welcome and I can help you!

**Comment by rafatosta** [comment]
> > I've already thought about doing it for installation and removal, similar to building the AppImage. But I'm out of time at the moment. Your contribution is welcome and I can help you!
> 
> I'd love to contribute, although I've never done this before.
> 
> However, if you direct me on how to, I certainly wouldn't mind.

Come to think of it, the same problem with AppImage will occur. PyQt6 packaging will not be complete for all distros, and for some distros the package names are different.

There is no standardization in the packaging of PyQt6 and WebEngine. So, it is unfeasible. 

Honestly, I don't understand the repulsion about the flatpak. Works perfectly well!
