### ISSUE TITLE
Zapzap is not my default whatsapp APP.. what gives?

### ISSUE THREAD

**Issue by tp1050** [rafatosta/zapzap#224]
I just installed ZapZap unto Ubuntu 24....  because it told me itself to do it , if I wish to use whatsapp naitively 
now I am confronted by this weird error where it says it is not installed and I should use the web. 

I am not even sure what is the command line for zapzap either......

so where do I go to change which line in which file to get things going?

PS: Apologies for the atrociousness English I am NeuroAtypicoAbNormal

**Comment by rafatosta** [comment]
> I just installed ZapZap unto Ubuntu 24.... because it told me itself to do it , if I wish to use whatsapp naitively now I am confronted by this weird error where it says it is not installed and I should use the web.
> 
> I am not even sure what is the command line for zapzap either......
> 
> so where do I go to change which line in which file to get things going?
> 
> PS: Apologies for the atrociousness English I am NeuroAtypicoAbNormal

I don't understand what your problem is. Could you send a screenshot or video of the problem?
