### ISSUE TITLE
Closes soon after opening (Wayland with Nvidia proprietary drivers)

### ISSUE THREAD

**Issue by Filip-Anicic** [rafatosta/zapzap#226]
Few seconds after opening the application with my messages being loaded. The application closes without any message.
Is there a way to fix this as I was looking for a good WhatsApp client on Linux?

Linux
flatpack 5.3.7
Fedora 40 Workstation
Gnome 46 DE

**Comment by rafatosta** [comment]
> Few seconds after opening the application with my messages being loaded. The application closes without any message. Is there a way to fix this as I was looking for a good WhatsApp client on Linux?
> 
> Linux flatpack 5.3.7 Fedora 40 Workstation Gnome 46 DE

Run via command line and check for errors, please

`flatpak run com.rtosta.zapzap`

**Comment by rafatosta** [comment]
I'm using Fedora Workstation too and I don't have a problem. I believe that the log of your execution can inform what is the problem with your machine

**Comment by Filip-Anicic** [comment]
```qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name is not activatable")
The Wayland connection experienced a fatal error: Protocol error
```

**Comment by rafatosta** [comment]
> This is the output I get in the terminal
> ```qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
> QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
> QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name is not activatable")
> The Wayland connection experienced a fatal error: Protocol error
> ```

Do you have Nvidia?

Try switching to X11 via flatsel or using the copr version

**Comment by Filip-Anicic** [comment]
Yes I have Nvidia proprietary drivers.
The suggestion to use Flatseal and disable Wayland windowing system, while keeping X11 windowing system and fallback seems to work.

Thanks

**Comment by Filip-Anicic** [comment]
Should I keep the issue open since the Wayland bug is not fixed yet?

**Comment by rafatosta** [comment]
> Should I keep the issue open since the Wayland bug is not fixed yet?

Yes. I'm about to buy a new notebook with NVidia, so I can provide "better" support for it. Let's wait and see.

**Comment by rafatosta** [comment]
> > Should I keep the issue open since the Wayland bug is not fixed yet?
> 
> Yes. I'm about to buy a new notebook with NVidia. Let's wait and see.

**Comment by sergiotca** [comment]
Hi guys, same issue here (Wayland).
I just wanted to add onto Filip's documentation with a bit longer log:

```
[sergiotca@fedora ~]$ flatpak run com.rtosta.zapzap
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name is not activatable")
js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
The Wayland connection experienced a fatal error: Protocl error
```

There are no crashes if I run it on X11 though (`flatpak nosocket=wayland run com.rtosta.zapzap`).
So... Wayland issue, perhaps? 


System:
-App Flatpak 5.3.7
-Fedora 40
-Gnome 46 + Wayland
-Nvidia Driver 560.35.03

**Comment by rafatosta** [comment]
> Hi guys, same issue here (Wayland). I just wanted to add onto Filip's documentation with a bit longer log:
> 
> ```
> [sergiotca@fedora ~]$ flatpak run com.rtosta.zapzap
> qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
> QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
> QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name is not activatable")
> js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
> js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
> js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
> QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
> The Wayland connection experienced a fatal error: Protocl error
> ```
> 
> There are no crashes if I run it on X11 though (`flatpak nosocket=wayland run com.rtosta.zapzap`). So... Wayland issue, perhaps?
> 
> System: -App Flatpak 5.3.7 -Fedora 40 -Gnome 46 + Wayland -Nvidia Driver 560.35.03

Yes, it's a Wayland and Nvidia problem, unfortunately.

**Comment by rafatosta** [comment]
duplicate: Can't run on Wayland #215
