### ISSUE TITLE
Shortcut for settings tab

### ISSUE THREAD

**Issue by gumbax3455** [rafatosta/zapzap#229]
Hi,
i hided the settings tab of ZapZap but now I want to change something in there, but i didn't remember the shortcut for them. Can someone tell me what is was? And maybe add that to the readme file.

**Comment by rafatosta** [comment]
> Hi, i hided the settings tab of ZapZap but now I want to change something in there, but i didn't remember the shortcut for them. Can someone tell me what is was? And maybe add that to the readme file.

Access settings via the tray icon or Ctrl + P.
