### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by frankor84** [rafatosta/zapzap#23]
ZapZap always starts in light mode, even if dark mode was selected the session before. Even it shows after the start, that dark mode is enabled but it shows the light theme. It is possible to change to dark theme after all.

I am running Pop!_OS 22.04 with Gnome 42 on Wayland.

**Comment by rafatosta** [comment]
I did not understand your question. Does the Dark mode work or not?
Starting in light mode and passing to the dark is not a bug, as it starts in light mode and only after, as defined in the user settings, or not the dark mode is applied.

**Comment by ahopkins** [comment]
FWIW, it seems that during startup there is a flash of dark before it switches to light. Here is an example of what i mean. It is a fresh start. I navigated to settings and it shows that I selected dark, but it obviously is not.

![image](https://user-images.githubusercontent.com/166269/166268940-15ca3b14-6a45-40e7-b25e-c62fbd68a067.png)

**Comment by rafatosta** [comment]
Apparently the error is on my side in not making the app settings menu clear.

On the left center of the screen there is a bar that gives access to zapzap settings (not whatsapp).
![image](https://user-images.githubusercontent.com/18619894/166294779-2595bc37-a6c3-4368-91e5-172e865b9355.png)

Thus, it is possible to define the theme and make it persistent.
![image](https://user-images.githubusercontent.com/18619894/166294982-90ce46dc-e940-4bd8-b086-9f7395f0ce19.png)

I'm working on a way to make the menu more visible and improve the way the settings are applied.

**Comment by frankor84** [comment]
Sorry for my delay. The issue was explained very well und thanks to your support, I found these special settings. I really did not even notice that bar.

So thanks for your help and good job! Zapzap is my favourite client :)

**Comment by rickschippers** [comment]
I came here for the same issue. Had never seen that settings option before. But it works fine when setup in there.
