### ISSUE TITLE
Stopped working on Linux Mint 

### ISSUE THREAD

**Issue by brunodmn** [rafatosta/zapzap#231]
Ap Suddenly stopped working, I already uninstalled and removed residual files. No succes.

My system info:
![image](https://github.com/user-attachments/assets/04ab8e11-5aa9-4746-824f-a954bf6e9f6a)

App Stuck on this screen:
![image](https://github.com/user-attachments/assets/b0f36af4-e704-4d1b-8401-33bb1b42ccf1)

Sometimes

**Comment by rafatosta** [comment]
> Ap Suddenly stopped working, I already uninstalled and removed residual files. No succes.
> 
> My system info:
> ![image](https://github.com/user-attachments/assets/04ab8e11-5aa9-4746-824f-a954bf6e9f6a)
> 
> App Stuck on this screen:
> ![image](https://github.com/user-attachments/assets/b0f36af4-e704-4d1b-8401-33bb1b42ccf1)
> 
> Sometimes 
> 

Still not working?

**Comment by AxeldeWater** [comment]
ZapZap works for me in Linux Mint 22... So it should be either a personal circumstance or a specific to that version of Mint.

**Comment by brunodmn** [comment]
Sry for late reply, it started working again some days later..No sure what happened or fixed it..so, no use for this thread. I will close id, thank you for your attention.
