### ISSUE TITLE
Hide messages.

### ISSUE THREAD

**Issue by liptech** [rafatosta/zapzap#235]
It's actually not a problem, I want to know how to blur messages that are not being read on ZAPZAP.

Thank you in advance to the team

**Comment by rafatosta** [comment]
I can't understand your doubt, excuse

**Comment by liptech** [comment]
![ZAPZAP](https://github.com/user-attachments/assets/06390fb8-a424-4d4a-92e7-58116583e12d)
I would like to do this so that other people around cannot see the messages, leaving them blurred. 
On Web Whatsapp there is an extension that, added to Chrome, hides the messages and when you hover the mouse they appear. 
something like this. 
Is it possible?

**Comment by rafatosta** [comment]
> ![ZAPZAP](https://private-user-images.githubusercontent.com/80398434/372495152-06390fb8-a424-4d4a-92e7-58116583e12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTQ2NDgsIm5iZiI6MTcyNzc5NDM0OCwicGF0aCI6Ii84MDM5ODQzNC8zNzI0OTUxNTItMDYzOTBmYjgtYTQyNC00ZDRhLTkyZTctNTgxMTY1ODNlMTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0NTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhM2UxY2IyZjU0YWUwYWY2NWZiYjk0YmMwNjhkMTQ0OWQ1NmI2ZGU1ZWUwMjJjMzFhZWNjZGIxM2I4N2Y3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5vrL-BGntmyFnMueivZASjFWIc12UBLbFzBrET-b7G4) I would like to do this so that other people around cannot see the messages, leaving them blurred. On Web Whatsapp there is an extension that, added to Chrome, hides the messages and when you hover the mouse they appear. something like this. Is it possible?

What extension? I can think of something if it is viable

**Comment by liptech** [comment]
https://chromewebstore.google.com/detail/wa-web-plus-by-elbruz-tec/ekcgkejcjdcmonfpmnljobemcbpnkamh
This is the one that works best.
