### ISSUE TITLE
persistent notification in ubuntu dock icon

### ISSUE THREAD

**Issue by ryansmith547** [rafatosta/zapzap#238]
Hello, on Ubuntu 24.04 Noble running on RasPi 5 (arm64), the unread message indicator on the ZapZap icon in the Ubuntu dock remains persistently a "1" with all messages read. Refreshing the window does not eliminate the notification counter showing "1". The icon in the tray, however, will accurately represent the number of unread messages, up to all read (with no notification showing). So looking to resolve the issue with the dock icon, and possible conflict with the tray notification counter, thank you.

![image](https://github.com/user-attachments/assets/faed1528-8c79-4257-986e-3ff6f2cd8689)
![image](https://github.com/user-attachments/assets/c1119035-ae45-48ef-8915-cdd2a34034ea)

**Comment by ryansmith547** [comment]
Is there any issue, such as lag, with messages not showing as read on your mobile phone? Which may be affecting the notification counter in zapzap....

**Comment by ryansmith547** [comment]
Edit: after some inspection it appears that the ZapZap dock icon will will display a "1" unread notification based on the Ubuntu system "ZapZap started in background" notification. Then the "1" unread message notification will disappear only once that Ubuntu system notification is cleared. @rafatosta can this be labeled as a bug with proposed solution that the dock icon behaviour is changed to not reflect the system notification as an unread message?

![Screenshot from 2024-10-12 12-53-02](https://github.com/user-attachments/assets/d74d8e61-b379-4028-8248-60b133d5fbbd)
↓ (with system notification cleared)
![image](https://github.com/user-attachments/assets/5ce71757-a1c6-4aaf-914d-eb5a25100cee)

**Comment by rafatosta** [comment]
> Edit: after some inspection it appears that the ZapZap dock icon will will display a "1" unread notification based on the Ubuntu system "ZapZap started in background" notification. Then the "1" unread message notification will disappear only once that Ubuntu system notification is cleared. @rafatosta can this be labeled as a bug with proposed solution that the dock icon behaviour is changed to not reflect the system notification as an unread message?
> 
> ![Screenshot from 2024-10-12 12-53-02](https://private-user-images.githubusercontent.com/15360016/375952310-d74d8e61-b379-4028-8248-60b133d5fbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzEyNjEsIm5iZiI6MTcyODczMDk2MSwicGF0aCI6Ii8xNTM2MDAxNi8zNzU5NTIzMTAtZDc0ZDhlNjEtYjM3OS00MDI4LTgyNDgtNjBiMTMzZDVmYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDExMDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZTNiYmU1NGEyZjIyZTg4ODk5MWUwZTkyZGRlYWY3MjAyYTY5YjcwMWU5NDEwM2M0ZDgyNWQ1YjMzODE0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WUhXkXApLLBfXOI6HqTB4W4REOZi5io_sv5j5nmnqIA) ↓ (with system notification cleared) ![image](https://private-user-images.githubusercontent.com/15360016/375952351-5ce71757-a1c6-4aaf-914d-eb5a25100cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzEyNjEsIm5iZiI6MTcyODczMDk2MSwicGF0aCI6Ii8xNTM2MDAxNi8zNzU5NTIzNTEtNWNlNzE3NTctYTFjNi00YWFmLTkxNGQtZWI1YTI1MTAwY2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDExMDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNDVlZDM5YTljYzQwYzcwMWY2ZTg1ZmMwYzIxM2Q4MjlmZTU4OTI4MjAyNWVhMDQ1NWRlMDg0NDNlMmQyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sabz2Kj1gbeXTrbzNjEpYPL0UGV4rHBqDhZQMIeMc_A)

Disable background running notification in settings!

**Comment by rafatosta** [comment]
I have no way to change the behavior of Ubuntu Dock, so I recommend that you disable the dock notification count.

**Comment by ryansmith547** [comment]
> I have no way to change the behavior of Ubuntu Dock, so I recommend that you disable the dock notification count.

Thanks, appreciate your work on the app and taking the time to comment :)
