### ISSUE TITLE
Muito obrigado!

### ISSUE THREAD

**Issue by raulgrangeiro** [rafatosta/zapzap#242]
Parceiro, esse app tem sido ótimo pra mim, queria te agradecer por criar e manter esse projeto. É o melhor app de WhatsApp que utilizei no Linux, tem todas as funções da versão desktop para Windows, com exceção de ligações porque não suporta.

Tudo funciona direitinho, até mesmo os links de navegador abrem diretamente nele, e é o único onde as notificações funcionam direito, em que quando você clica abre direto na conversa. Uma coisa muito legal que vi só nele também é o fato de que quando você clica no ícone minimizado para abrir ele não abre na última conversa que o usuário esteve, mas abre na tela inicial do WhatsApp Web evitando que abra uma conversa que não queria abrir.

E funciona perfeitamente no Wayland com o Ubuntu 24.04 e hardware AMD.

Essa atenção aos detalhes me deixou tão feliz em ver o app. Obrigado, amigo! Assim que puder mando um pix pra ajudar o senhor, da mesma forma que me ajudou muito com esse app.

Deus o abençoe!

**Comment by rafatosta** [comment]
Muito obrigado pelo reconhecimento!! 
😊
