### ISSUE TITLE
Gostei muito do app, mas como posso corrigir esse problema?

### ISSUE THREAD

**Issue by Jebyto** [rafatosta/zapzap#244]
O app é uma ótima maneira de usar o whatsapp no linux, mas estou com um problema, que meu mouse fica muito pequeno dentro do app, eu uso o linux mint 22 cinnamon.
![WhatsApp Image 2024-10-31 at 10 25 42](https://github.com/user-attachments/assets/04ad0adf-540c-4579-9fcf-137fe12eddf5)
![WhatsApp Image 2024-10-31 at 10 25 42 (1)](https://github.com/user-attachments/assets/803e2f8a-c635-490d-97ff-249a80a45b46)

**Comment by rafatosta** [comment]
Olá, José.

Isso é um "problema" de integração do Flatpak. Para contornar abra o Flatseal e crie duas variáveis de ambiente:
Para definir o tamanho: 
`XCURSOR_SIZE=24`

e para definir o tema:
` XCURSOR_THEME= 'Fluent-cursor'
`
Coloque exatamente o mesmo nome do seu tema em "XCURSOR_THEME"

**Comment by Jebyto** [comment]
Deu certo, valeu
