### ISSUE TITLE
First account bug

### ISSUE THREAD

**Issue by natahsp-mint** [rafatosta/zapzap#245]
![Screenshot from 2024-11-04 09-45-05](https://github.com/user-attachments/assets/9ddab0f2-03c4-4eae-aac8-ba97fa54ade7)

Hi, 

The first zap account option is loading forever. It's not actually connected to either my whatsapp accounts because I assured to remove it, trying to fix the problem. But the account is still loading forever, and never actually openning anything. I can't even delete this one, due to being the first/original account to login in.
I already deleted the software and cleaned it all through the terminal, updated, upgraded... etc. But nothing.
Please help!!

**Comment by rafatosta** [comment]
I can't reproduce it. I recommend that you remove the entire app folder in .var and run it again.
