### ISSUE TITLE
Audio message playback is broken

### ISSUE THREAD

**Issue by 43615** [rafatosta/zapzap#246]
After some recent system update, I can't play audio messages in the client (play button doesn't do anything). It works with all other clients I've tried. As a workaround, I'm still able to download+play them locally.
Is there a log file I can check?

**Comment by rafatosta** [comment]
> After some recent system update, I can't play audio messages in the client (play button doesn't do anything). It works with all other clients I've tried. As a workaround, I'm still able to download+play them locally. Is there a log file I can check?

I'm facing this same problem and I still haven't been able to identify the reason. 

You are using via copr, right? In Flatpak it is working correctly, I suggest you use it in flatpak until I can fix it.

**Comment by Pegoku** [comment]
I'm using the AUR package and having the same problem

**Comment by RicardoPQ-com** [comment]
> I'm using the AUR package and having the same problem

Same here

**Comment by rafatosta** [comment]
Use the Flatpak version!!

Please note that the AUR version is not maintained by me.

**Comment by 43615** [comment]
I was also using the AUR version. The Flatpak version works fine, so there's probably something wrong with one of the AUR dependencies.

**Comment by rafatosta** [comment]
> I was also using the AUR version. The Flatpak version works fine, so there's probably something wrong with one of the AUR dependencies.

The problem is in the PyQt6 version.
I always recommend flatpak, but if you want to use AUR, advise to downgrade the PyQt6 version to the latest 6.7.
