### ISSUE TITLE
tryicon color on dark mode

### ISSUE THREAD

**Issue by armando-basile** [rafatosta/zapzap#247]
Hi all,
could be use more white or gray light icon on dark theme desktop (in my case cinnamon with Adapta-Nokto theme) ?

![immagine](https://github.com/user-attachments/assets/e1c4cb93-555b-460b-801d-35c0ce5e9570)

**Comment by rafatosta** [comment]
This option exists in Personalization!
![image](https://github.com/user-attachments/assets/eeb236cb-d14a-468c-b819-418e478ceb2d)
