### ISSUE TITLE
'Open' and 'Save File' dialogs don't honor dark color scheme

### ISSUE THREAD

**Issue by mielouk** [rafatosta/zapzap#250]
As we strive to improve zapzap, I found some more little bugs. One of which is the colour scheme of the Qt/KDE layout that doesn't honour the selected dark theme. Probably because of the Flatpak/Sandbox, although the path and the type fields do.

While doing this I also found that right clicking on a picture to save it doesn't open the dialog to save the picture. Should I open a separate issue for this?

![2024-11-11-171700_grim](https://github.com/user-attachments/assets/8d451cef-5763-462e-a818-4607ea26febc)
![2024-11-11-171610_grim](https://github.com/user-attachments/assets/b89d1165-a2e4-4e1a-ab8d-44bbd18324af)

**Comment by rafatosta** [comment]
This is Flatpak's lack of integration and not Zapzap. If you know how to solve through environmental variables I will thank you

**Comment by mielouk** [comment]
[This documentation might help.](https://docs.flatpak.org/en/latest/desktop-integration.html)

Instructions for Qt themes

There are a few Qt theme extensions packaged on Flathub. To see a list, you can run:

$ flatpak remote-ls --columns=application flathub | grep org.kde.KStyle

Then you can install the theme with:

$ flatpak install flathub org.kde.KStyle.Foo

replacing Foo with the name of the desired theme. The theme needs to be available for the KDE runtime branch used by the application.

Gtk look and feel in Qt applications
On Wayland, starting from the 5.15-22.08+ and 6.5+ branches of the org.kde.Platform runtime, org.kde.WaylandDecoration.QAdwaitaDecorations and org.kde.WaylandDecoration.QGnomePlatform-decoration need to be installed. Please see the upstream [usage](https://github.com/FedoraQt/QAdwaitaDecorations?tab=readme-ov-file#usage) instructions as well.


The [Arch Wiki](https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QAdwaitaDecorations) seems to be outdated unfortunately.

**Comment by rafatosta** [comment]
> [This documentation might help.](https://docs.flatpak.org/en/latest/desktop-integration.html)
> 
> Instructions for Qt themes
> 
> There are a few Qt theme extensions packaged on Flathub. To see a list, you can run:
> 
> $ flatpak remote-ls --columns=application flathub | grep org.kde.KStyle
> 
> Then you can install the theme with:
> 
> $ flatpak install flathub org.kde.KStyle.Foo
> 
> replacing Foo with the name of the desired theme. The theme needs to be available for the KDE runtime branch used by the application.
> 
> Gtk look and feel in Qt applications On Wayland, starting from the 5.15-22.08+ and 6.5+ branches of the org.kde.Platform runtime, org.kde.WaylandDecoration.QAdwaitaDecorations and org.kde.WaylandDecoration.QGnomePlatform-decoration need to be installed. Please see the upstream [usage](https://github.com/FedoraQt/QAdwaitaDecorations?tab=readme-ov-file#usage) instructions as well.
> 
> The [Arch Wiki](https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QAdwaitaDecorations) seems to be outdated unfortunately. Though this might be helpful with regards to environment variables:
> 
> QAdwaitaDecorations
> 
> QAdwaitaDecorations is Qt decoration plugin implementing Adwaita-like client-side decorations for [Wayland](https://wiki.archlinux.org/title/Wayland). It can be installed with the [qadwaitadecorations-qt5](https://aur.archlinux.org/packages/qadwaitadecorations-qt5/)AUR and [qadwaitadecorations-qt6](https://aur.archlinux.org/packages/qadwaitadecorations-qt6/)AUR packages. After installing, set QT_WAYLAND_DECORATION=adwaita to environment variable. QWhiteSurGtkDecorations
> 
> QWhiteSurGtkDecorations is Qt decoration plugin implementing WhiteSur-gtk-like client-side decorations for [Wayland](https://wiki.archlinux.org/title/Wayland). It can be installed with the [qwhitesurgtkdecorations-qt5](https://aur.archlinux.org/packages/qwhitesurgtkdecorations-qt5/)AUR and [qwhitesurgtkdecorations-qt6](https://aur.archlinux.org/packages/qwhitesurgtkdecorations-qt6/)AUR packages. After installing, set QT_WAYLAND_DECORATION=whitesur-gtk to environment variable.

As Fedora comes with all the packages installed, it works well in the tests I did. Therefore, it is a configuration outside Zapzap, in the distro itself.
