### ISSUE TITLE
[Feature Request] Option to ignore muted chats / groups in the tray notification counter

### ISSUE THREAD

**Issue by LittleNyanCat** [rafatosta/zapzap#251]
I am the kind of person that likes to keep their notifications clean, so that when I have a notification I know there's something to read/reply to that I haven't yet.

The behavior of the official Whatsapp App on Windows only shows the notification counter for unread messages from conversations that aren't muted, which (to me) makes the most sense (given that you may be in some groups where you don't often participate/don't want to be actively notified about, so you mute them, and thus it makes no sense for them to appear in the notification counter). ZapZap doesn't have this behavior, thus I'm asking for it to be added as an option for those of us who prefer it.

**Comment by rafatosta** [comment]
> I am the kind of person that likes to keep their notifications clean, so that when I have a notification I know there's something to read/reply to that I haven't yet.
> 
> The behavior of the official Whatsapp App on Windows only shows the notification counter for unread messages from conversations that aren't muted, which (to me) makes the most sense (given that you may be in some groups where you don't often participate/don't want to be actively notified about, so you mute them, and thus it makes no sense for them to appear in the notification counter). ZapZap doesn't have this behavior, thus I'm asking for it to be added as an option for those of us who prefer it.

As a description of Zapzap, WhatsApp Web is used. So, you need to request this feature for Meta. 
I understand that it seems to be part of Zapzap, but I will not be doing any manipulation of the page. Thus maintaining the minimum integration and security.

**Comment by carsten88** [comment]
Awww that is too bad. I wanted to ask the same thing, but then for the unread-messages on the zapzap-button on the panel.

Thank you for this nice software.
