### ISSUE TITLE
Audio not working.

### ISSUE THREAD

**Issue by srxavi** [rafatosta/zapzap#253]
Since a few day ago, Whatsapp audios do not work. When I click on the play button nothing happens.

**Comment by rafatosta** [comment]
> Since a few day ago, Whatsapp audios do not work. When I click on the play button nothing happens.

I'm aware of this issue. Please use the Flatpak version!

**Comment by srxavi** [comment]
Thanks! I can confirm that it works in the Flatpak version.

**Comment by evilsh3ll** [comment]
> > Since a few day ago, Whatsapp audios do not work. When I click on the play button nothing happens.
> 
> I'm aware of this issue. Please use the Flatpak version!

is there any eta for the fix?

**Comment by rafatosta** [comment]
> > > Since a few day ago, Whatsapp audios do not work. When I click on the play button nothing happens.
> > 
> > 
> > I'm aware of this issue. Please use the Flatpak version!
> 
> is there any eta for the fix?

It's a PyQt 6.8 issue and not a Zapzap issue. So I don't know when it will be resolved.

**Comment by BasitAli** [comment]
Just installed the flatpak version, Still no audio.

**Comment by rafatosta** [comment]
> Just installed the flatpak version, Still no audio.

It's with audio yes!

**Comment by BasitAli** [comment]
I mean audio is not working for me with the flatpak version as well.

**Comment by rafatosta** [comment]
> I mean audio is not working for me with the flatpak version as well.

I repeat, there are no audio problems in Flatpak. If it is not working for you, then something on your side (your distribution) happening.

 Please record a video showing that it is not working. Otherwise, I can't do anything else.

**Comment by marcelarie** [comment]
Hi, for me the problem is that I can't press the play button of the audios. Is this the same behavior that you are talking about in this issue?

I used the AUR package: https://aur.archlinux.org/packages/zapzap

**Comment by rafatosta** [comment]
> Hi, for me the problem is that I can't press the play button of the audios. Is this the same behavior that you are talking about in this issue?
> 
> This happens in both the stable and git packages in the AUR: https://aur.archlinux.org/packages/zapzap https://aur.archlinux.org/packages/zapzap-git
> 
> For now I will use the flatpak version.

The AUR is not officially supported, so it does not complain about the AUR here. Talk directly to your maintainer !!

**Comment by ThePirate42** [comment]
@rafatosta Was this closed because the upstream bug is solved?

**Comment by rafatosta** [comment]
> @rafatosta Was this closed because the upstream bug is solved?
No. It's just not my responsibility to correct it. The stable version with all features working will always be available for Zapzap!
