### ISSUE TITLE
Feature Request: Add minor version display in ZapZap app about section

### ISSUE THREAD

**Issue by GreyStinger** [rafatosta/zapzap#256]
# Request

Add minor versions to the ZapZap about section that are linked to tagged releases.

## Reason

It can be hard to know when the zapzap minor version is not up to date especially on controlled systems.

## Comment

I would be more than happy to implement this if it is a reasonable request.

**Comment by rafatosta** [comment]
The question is: why if flatpak already does it for you?

**Comment by rafatosta** [comment]
> I hadn't thought about that, I'll have a look into that and get back to this.

![image](https://github.com/user-attachments/assets/8449b82a-fcc0-4d87-85e8-506611413717)
