### ISSUE TITLE
Two side bars

### ISSUE THREAD

**Issue by adam-tj** [rafatosta/zapzap#257]
There are two sidebars when using ZapZap. One which is the one that appears on the regular WhatsApp Web and then the one which comes with ZapZap. Looking at the gallery on the ZapZap website it seems that there should only be one sidebar.

I am using using ZapZap version 5.3.1 on openSUSE Tumbleweed.

![zapzap](https://github.com/user-attachments/assets/9eb9bb72-acf9-4b5c-a482-96fdf5fe3403)

**Comment by rafatosta** [comment]
> There are two sidebars when using ZapZap. One which is the one that appears on the regular WhatsApp Web and then the one which comes with ZapZap. Looking at the gallery on the ZapZap website it seems that there should only be one sidebar.
> 
> I am using using ZapZap version 5.3.1 on openSUSE Tumbleweed.
> 
> ![zapzap](https://private-user-images.githubusercontent.com/9314405/387161324-9eb9bb72-acf9-4b5c-a482-96fdf5fe3403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDI4NDgsIm5iZiI6MTczMTk0MjU0OCwicGF0aCI6Ii85MzE0NDA1LzM4NzE2MTMyNC05ZWI5YmI3Mi1hY2Y5LTRiNWMtYTQ4Mi05NmZkZjVmZTM0MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMTUwOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg5NjdiOGQzMDA0MGQxZTg4NTBhODM5NmQ3ZGExNjA4N2FiNTVhMjE3OGVlNGEwNzQwYTM2ZmY2YWI1ODAzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PVZHw9hLqGrJn0NsBWU8tB4a7HTdS5efVg4OvOGFVYs)

Look in the settings for an option to hide when there is only one user
