### ISSUE TITLE
ZapZap crashes on Fedora 40/41 after clicking to focus window

### ISSUE THREAD

**Issue by burgermanbrown** [rafatosta/zapzap#258]
https://github.com/user-attachments/assets/78512b78-4c01-404f-9188-ced9b275d68d

Tried disabling my extensions with no luck. If there is a log I can supply please let me know!

**Comment by rafatosta** [comment]
Do you have Nvidia? In flatseal, uncheck the Wayland option

**Comment by burgermanbrown** [comment]
> Do you have Nvidia? In flatseal, uncheck the Wayland option

Was not aware of flatseal. Thank you! 

I do have Nvidia. GTX 1080. I gave your recommendation a try and it gets hung up on the loading chats screen. Any suggestions?

![Screenshot From 2024-11-19 20-16-58](https://github.com/user-attachments/assets/6f4c7596-ab98-4d9b-88fe-5cf06958e01b)

**Comment by burgermanbrown** [comment]
Nevermind, I just unlinked my session in the app and tried again. We're good to go!
