### ISSUE TITLE
Crashes when on (Ubuntu) Wayland

### ISSUE THREAD

**Issue by dm30** [rafatosta/zapzap#259]
Hi! Now that Ubuntu 24.10 defaults to Wayland on NVIDIA hardware, I noticed that ZapZap closes down when you first bring up the app to the front. Then does not open at all. Are you aware? Thank you.

**Comment by rafatosta** [comment]
> Hi! Now that Ubuntu 24.10 defaults to Wayland on NVIDIA hardware, I noticed that ZapZap closes down when you first bring up the app to the front. Then does not open at all. Are you aware? Thank you.

As far as I know, this happens on non-hybrid GPU hardware. Either way, regardless of the distribution, it's a problem on Nvidia's side.

To resolve, uncheck Wayland no Flatseal.

**Comment by dm30** [comment]
Easy breeze. Seems solved. Can't be patched so does not rely on Wayland under this (NVIDIA GPU) circumstances. Thx
