### ISSUE TITLE
There is no Bosnian file in /po folder

### ISSUE THREAD

**Issue by MuxBH28** [rafatosta/zapzap#260]
Hello,

I would like to translate zapzap to Bosnian, but there is no po file available.
Will it be added?

Many thanks

**Comment by MuxBH28** [comment]
Funny thing is that both file names are in use, but I think the more standard one is 
`bs`

Thank You for fast reply :)

**Comment by rafatosta** [comment]
> Funny thing is that both file names are in use, but I think the more standard one is `bs`
> 
> Thank You for fast reply :)

The file is available for the translation. When finished it makes a pull request so I can apply the translation and release an update.

https://github.com/rafatosta/zapzap/blob/main/po/bs.po

 Thanks for the collaboration
