### ISSUE TITLE
Wont launch since newest update

### ISSUE THREAD

**Issue by EisregenHaha** [rafatosta/zapzap#261]
I have to set Wayland manually with Flatseal to get it to launch.
Am on Fedora 41 with Hyprland and Nvidia
If ya need any more info just ask

**Comment by rafatosta** [comment]
> I have to set Wayland manually with Flatseal to get it to launch. Am on Fedora 41 with Hyprland and Nvidia If ya need any more info just ask

There are issues with Nvidia, use on x11 for now!

**Comment by EisregenHaha** [comment]
> > I have to set Wayland manually with Flatseal to get it to launch. Am on Fedora 41 with Hyprland and Nvidia If ya need any more info just ask
> 
> There are issues with Nvidia, use on x11 for now!

well hyprland has no x11 lol, i'll just keep it on wayland ig

**Comment by rafatosta** [comment]
> > > I have to set Wayland manually with Flatseal to get it to launch. Am on Fedora 41 with Hyprland and Nvidia If ya need any more info just ask
> > 
> > 
> > There are issues with Nvidia, use on x11 for now!
> 
> well hyprland has no x11 lol, i'll just keep it on wayland ig

Sorry for not being clear, use x11 only on Zapzap through Flatseal.

**Comment by rafatosta** [comment]
See #215

**Comment by EisregenHaha** [comment]
> See #215

as i said yesterday i have already done this. my very first comment says 'have to set wayland through flatseal'
