### ISSUE TITLE
Can't send/play gifs

### ISSUE THREAD

**Issue by netronicus** [rafatosta/zapzap#265]
I'm using Fedora 41 and ZapZap from rpm repo, I can't attach gifs, I can search for them but when choosing one I'm getting "not supported" message.
From terminal I'm getting this error:
`js: Uncaught (in promise) UnableToPlayVideoError: Unable to play video. Reason: MEDIA_ERR_SRC_NOT_SUPPORTED: DECODER_ERROR_NOT_SUPPORTED
`

**Comment by rafatosta** [comment]
This is a problem with WhatsApp Web, so it is not a Zapzap problem.
