### ISSUE TITLE
Pergunta: É normal carregar o whatsapp web em inglês?

### ISSUE THREAD

**Issue by eltonfabricio10** [rafatosta/zapzap#266]
Parabéns pelo projeto! Ficou top!
Você conhece o PySide6 ?

**Comment by rafatosta** [comment]
> Parabéns pelo projeto! Ficou top!
> Você conhece o PySide6 ?
> 

Obrigado. 

Em algumas distros inicia em inglês, mas logo em seguida fica em português. É algo relacionado a página do WhatsApp Web, nada fora do normal. 

Conheço o PySide6 sim.

**Comment by rafatosta** [comment]
Inicialmente o ZapZap foi escrito em PySide6, porém, por causa de problemas com empacotamento em flatpak, mudei para o PyQt6 por oferecer maior compatibilidade com o flatpak e atualizações mais rápidas.

**Comment by eltonfabricio10** [comment]
> Em algumas distros inicia em inglês, mas logo em seguida fica em português. É algo relacionado a página do WhatsApp Web, nada fora do normal.

é isso mesmo, deu certo!
o que eu gostei mesmo foi a função de abrir links de whatsapp no zapzap ❤️
