### ISSUE TITLE
ZapZap module error in EndeavourOS

### ISSUE THREAD

**Issue by itjdel** [rafatosta/zapzap#276]
Hello.

In EndeavourOS KDE (wayland), with last update, Zapzap don't run...

Here is ther error from terminal: 

Traceback (most recent call last):
  File "/usr/bin/zapzap", line 5, in <module>
    from zapzap.__main__ import main
ModuleNotFoundError: No module named 'zapzap'

Thanks

**Comment by rafatosta** [comment]
> Hello.
> 
> In EndeavourOS KDE (wayland), with last update, Zapzap don't run...
> 
> Here is ther error from terminal:
> 
> Traceback (most recent call last): File "/usr/bin/zapzap", line 5, in from zapzap.**main** import main ModuleNotFoundError: No module named 'zapzap'
> 
> Thanks

Running in flatpak?

**Comment by itjdel** [comment]
Hello

Yes, from flatpak works... but i prefer AUR

Thanks

**Comment by rafatosta** [comment]
Read #189

**Comment by felipe-vf** [comment]
@rafatosta the issue was deleted. Could you please link the solution again?
