### ISSUE TITLE
Getting "UPDATE GOOGLE CHROME" message

### ISSUE THREAD

**Issue by vinibortoletto** [rafatosta/zapzap#29]
I'm unable to logging to WhatsApp. When I open ZapZap I get an error telling me to update Google Chrome.

Here's a screenshot:
https://i.imgur.com/2v2ehAc.png

**Comment by rafatosta** [comment]
sometimes this happens and it's not really Zapzap's fault. To solve press F5, please.
Sorry for the inconvenience.

**Comment by vinibortoletto** [comment]
Thanks! That worked.
