### ISSUE TITLE
Changing theme when opening

### ISSUE THREAD

**Issue by Allan-Bruno** [rafatosta/zapzap#31]
The theme automatically change when the app is closed and opened again

**Comment by rafatosta** [comment]
Is it possible to upload a video with such behavior? I use it every day and haven't noticed this described behavior. Thanks

**Comment by Allan-Bruno** [comment]
I should had left more details, sorry for the confusion, but anyways, that's basically what i mean:

https://user-images.githubusercontent.com/85714177/168447639-e7aeb460-a5c3-4d50-9258-38e0e41278c1.mp4

**Comment by rafatosta** [comment]
Cara, acessa essa barra lateral que você verá a opção de troca de tema! 
Notei que é BR, então vai em português mesmo. Tmj

**Comment by rafatosta** [comment]
Estou quase removendo essa opção do menu do aplicativo, pois está gerando muita confusão. Heheeh

**Comment by Allan-Bruno** [comment]
Vi agora, desculpa pelo issue desnecessário!
De qualquer forma fiquei mt feliz por ver um projeto BR no flathub 🇧🇷  🇧🇷  🇧🇷
