### ISSUE TITLE
Multiple empty tray icons on GNOME 42

### ISSUE THREAD

**Issue by EllBock** [rafatosta/zapzap#34]
When I lock the screen or suspend my PC, sometimes an empty tray icon is created together with the original tray icon. This also means that if I lock or suspend multiple times, you get more than one.

https://user-images.githubusercontent.com/46938039/171404957-703c737e-7746-4c81-aff3-fee65d333257.mp4

Some of these seem to open the main window of ZapZap, but some of them stop working. Exiting ZapZap removes the original tray icon, but not the empty ones, so I have to terminate the GNOME session to restore normal behavior.

I'm on Fedora 36 with GNOME 42 and AppIndicator extension, and I'm using the latest flatpak version of the app from Flathub.

**Comment by rafatosta** [comment]
I'm going to implement the tray icon deactivation and drop it now in v2.8.

**Comment by rafatosta** [comment]
Good luck with the report, because it took time to implement before releasing the new version.
Now available for download
![image](https://user-images.githubusercontent.com/18619894/171533821-0c7e6a62-c4b5-48a2-83ad-d5eaa4cb4ce3.png)
