### ISSUE TITLE
Problem while dragging window

### ISSUE THREAD

**Issue by dipanjan1992** [rafatosta/zapzap#37]
zapzap window can be resized but cannot be moved as its stuck in one place. Fedora 36 Workstation. Gnome version 42.2.

![Screenshot from 2022-06-08 12-32-42](https://user-images.githubusercontent.com/107064001/172559576-65d5db4b-199a-4d89-8378-e01b47d4e235.png)

**Comment by rafatosta** [comment]
Does the problem still persist? 
I also use the F36 WS and it works perfectly.

**Comment by dipanjan1992** [comment]
Yes it still persists, it seems like closing the window causes the issue. Opening zapzap after reboot shows minimize and move icon, but after closing it (hide on close option selected), those icons disappears and even right clicking the title bar has those options greyed out.

**Comment by rafatosta** [comment]
An example that everything is working.
Use NVidia or AMD, wayland or X11?
https://user-images.githubusercontent.com/18619894/173187511-853036ae-017e-4610-81fc-d35be750b006.mp4

**Comment by dipanjan1992** [comment]
Intel integrated, i3 10100, Wayland.
