### ISSUE TITLE
Wayland support for flatpak?

### ISSUE THREAD

**Issue by aleprovencio** [rafatosta/zapzap#38]
Hello!
Is there a way to run this app on `flatpak` through `wayland`? I've tried `sockets=wayland;!x11` and even setting `QT_QPA_PLATFORM=wayland` on the environment but it does not seem enough, currently getting this error message:
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was f
ound.
This application failed to start because no Qt platform plugin could be initialized.
Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhr
display, vnc, wayland-egl, wayland, xcb.
```

**Comment by rafatosta** [comment]
Br, né?
Ainda não tive tempo pra verificar a fundo o motivo desse erro. 
Até já consegui colocar pra funcionar no wayland, porém ficou muito instável renderização do WebView. Preciso até atualizar o PyQt6 no empacotamento, pois está um pouco desatualizado e quem sabe resolva algum desse problema. 

Não sei qual a diferença na prática (desempenho/privacidade/consumo) de um web app em wayland. Mas estou disposto a fazer funciona no wayland.

**Comment by aleprovencio** [comment]
Sim, BR! :)

Independente do que o Wayland traga de benefícios, acredito que não usar X ou Xwayland já é uma grande vantagem, ainda mais se falando de Flatpaks.

Parabéns pela app!

**Comment by simonsaysthis** [comment]
The benefit of Wayland will be that HiDPI users on Plasma (200% scaling) can use Zapzap without it looking blurry
