### ISSUE TITLE
Refresh button to avoid Chrome Upgrade needed issue

### ISSUE THREAD

**Issue by AndrewCSQ** [rafatosta/zapzap#4]
Sometimes ZapZap will show "Chrome Version is too old" issue. WhatsAppQT worked around this by having a refresh toggle that usually fixed it.

**Comment by rafatosta** [comment]
Thanks. I've been trying to solve this since yesterday and without success. I will look at WhatsAppQt. I still have a solution today. A simple and temporary solution is to delete the application folder in .var/app

**Comment by rafatosta** [comment]
Thanks a lot for the help. Worked perfectly!!!
I left the reload right after booting which is preventing the issue from happening. Also, I put actions on F5 key and context menu.

**Comment by AndrewCSQ** [comment]
That's awesome thanks for the quick fix. Let me know when a new version has been put up e.g. on Flathub - I'll be happy to test/verify and close the issue if it all works well

**Comment by rafatosta** [comment]
Correction already made, just wait.
Thanks for the feedback. =D
![image](https://user-images.githubusercontent.com/18619894/151982950-0688b2c3-631f-4900-996c-d42929fdc22f.png)

**Comment by ahopkins** [comment]
Still experiencing this.

```
ZapZap                                     com.rtosta.zapzap                                      2.2             stable       system
```

Deleting the directory does work, but is annoying and not a real solution because it loses all settings/config. Any other workarounds?

**Comment by rafatosta** [comment]
This week it reappeared, but only once for me. If you press F5 solve it, no need to remove system folder

**Comment by rafatosta** [comment]
> Still experiencing this.
> 
> ```
> ZapZap                                     com.rtosta.zapzap                                      2.2             stable       system
> ```
> 
> Deleting the directory does work, but is annoying and not a real solution because it loses all settings/config. Any other workarounds?

This week it reappeared, but only once for me. If you press F5 solve it, no need to remove system folder

**Comment by ahopkins** [comment]
I tried that. Sometimes it would work, sometimes not. Sometimes restarting worked, sometimes not.

**Comment by rafatosta** [comment]
> I tried that. Sometimes it would work, sometimes not. Sometimes restarting worked, sometimes not.

Very strange... I will investigate
