### ISSUE TITLE
Im losing neutral system tray icon

### ISSUE THREAD

**Issue by Geordinateur** [rafatosta/zapzap#43]
Hi, my tray icon have change to day, and i can't open Settings whit right click

**Comment by rafatosta** [comment]
Please provide more details like: distro, theme, etc.

**Comment by Geordinateur** [comment]
I using Archlinux with i3, and launch ZapZap witch `python -m zapzap` and I pulled repo already day.

![zapzap-no-parametres](https://user-images.githubusercontent.com/66678120/177089656-3b273efc-9a46-41df-b5e6-b89cde5a6f1c.png)
