### ISSUE TITLE
Preview for links not being generated properly

### ISSUE THREAD

**Issue by EkanshdeepGupta** [rafatosta/zapzap#46]
**Description**
When sending a message containing a link, the preview generated for the link does not fetch any details about the linked webpage. When pasting a link in a chat from a phone or web.whatsapp.com, WhatsApp generates a preview for the url including a title and thumbnail. However, for links sent via zapzap, the preview only contains the url.

**To Reproduce**
1. Go to any chat.
2. Copy a link to a website in the chat
3. Wait a couple of seconds for the preview to be generated
4. The preview merely has the URL, not the title or thumbnail.

**Expected behavior**
The generated preview should have the title and thumbnail.

**Screenshots**
Preview generated by zapzap:
![Screenshot from 2022-07-03 18-25-17](https://user-images.githubusercontent.com/13527018/177059578-dabd3de9-c8f5-48ff-9466-23ae75392df5.png)

Preview generated by WhatsApp on phone:
![Screenshot from 2022-07-03 18-25-40](https://user-images.githubusercontent.com/13527018/177059580-bb44392e-864f-48e7-b11f-2c898c08cd32.png)

**Environment**

 - Distro [ Fedora Linux 36 ]
 - Package [ Flatpak]
 - Desktop Environment or Window Manager [ Gnome 42.2 ]

**Comment by rafatosta** [comment]
Thanks for reporting! I don't receive or send many links and with that I didn't notice. First I have no idea how to do this, if you can help with some more technical information like problems I seem Or look for a solution and send a pull request I'll thank you.

**Comment by EkanshdeepGupta** [comment]
Hi @rafatosta, can you tell me what kind of technical information I can provide which will help figure out this issue? I would be happy to provide any information.

**Comment by rafatosta** [comment]
Like: How to load previewrew link in qwebview. Or if anyone has had this problem and how did you solve it?

**Comment by EkanshdeepGupta** [comment]
Most WhatsApp clients are just some kinds of wrappers around WhatsApp Web. It was my impression that all these features would not need to be directly implemented in clients. 

I am curious, how is zapzap implemented? I know I can look at the code, but thought it would be quicker to ask. If you could point me to the relevant places in the code which generates these previews, I might be able to help.

**Comment by rafatosta** [comment]
Receiving works, but sending does not.

![image](https://user-images.githubusercontent.com/18619894/177162820-a684ddaa-97d0-40f3-a1aa-406ea96e5ec4.png)

**Comment by rafatosta** [comment]
It's not my fault, it's just whatsapp. The same thing happens in the Android app.
