### ISSUE TITLE
Tiny symbolic tray icon in gnome

### ISSUE THREAD

**Issue by musiclover382** [rafatosta/zapzap#53]
Hey, first of all thanks for this awesome application!!

As you can see, the symbolic icon looks very small in gnome, you can compare it with the dropbox one (appindicator extension) and the native system icons.
![image](https://user-images.githubusercontent.com/95233098/179195332-457254ec-1044-4988-a48f-2b2833efc8a6.png)

**Comment by rafatosta** [comment]
[New symbolic icons](https://github.com/rafatosta/zapzap/commit/7bef78ab3b5dcde6ec5f23873ddc5615b05df054)
