### ISSUE TITLE
Show menu bar when pressing Alt

### ISSUE THREAD

**Issue by musiclover382** [rafatosta/zapzap#55]
In other applications like Firefox, if the menu bar is hidden you can press Alt to temporarily reveal it. It would be great if ZapZap behaved the same way when the Hide menu bar option is enabled.

**Comment by rafatosta** [comment]
Initially I thought of doing it this way, but as it is a little used option on a daily basis, I let it go. With the new window decoration, this menu disappears.

**Comment by musiclover382** [comment]
Alright. Is the new window decoration already on main? I don't have it on flatpak + gnome

**Comment by rafatosta** [comment]
Yup. I released as version 3.0 a few days ago

**Comment by musiclover382** [comment]
Oh, alright. I guess this is a separate bug then. I get no hamburger menu in the topbar

**Comment by rafatosta** [comment]
you're not using it in flatpak is that it?

**Comment by musiclover382** [comment]
It's a flatpak indeed
