### ISSUE TITLE
Feature request: show number of new messages in tray icon

### ISSUE THREAD

**Issue by musiclover382** [rafatosta/zapzap#56]
I don't know if it's doable, but I believe I saw this somewhere... Maybe we have 11 different icons and from 10 on we instead show 9+

**Comment by rafatosta** [comment]
It is necessary to join a String with an SVG in the routine that checks the number of notifications and shows the icon.

https://github.com/rafatosta/zapzap/blob/main/zapzap/controllers/main_window_components/tray_icon.py

**Comment by rafatosta** [comment]
Coming... 
![image](https://user-images.githubusercontent.com/18619894/179617867-2affdd00-d157-4a7d-a85b-1bdf11cac9d5.png)

**Comment by filipesaraiva** [comment]
Hi, first all thank you for this great software! Sorry for write in a past issue, but could be possible to disable the counting of unread messages on system tray? Maybe it could be optional. Thank you!

**Comment by rafatosta** [comment]
> Hi, first all thank you for this great software! Sorry for write in a past issue, but could be possible to disable the counting of unread messages on system tray? Maybe it could be optional. Thank you!

Sem problema... vou fazer e deixar a opção nas configurações avançadas!

**Comment by rafatosta** [comment]
Prontinho....

![image](https://github.com/rafatosta/zapzap/assets/18619894/71ec7736-e852-44b9-b97a-9c1f20d31505)

**Comment by filipesaraiva** [comment]
Caramba mano... como diriam os jovens, tu é brabo heim :joy::joy::joy::joy:

Parabéns, muito obrigado demais!!!
