### ISSUE TITLE
No window decoration in GNOME

### ISSUE THREAD

**Issue by musiclover382** [rafatosta/zapzap#58]
I don't get any hamburger menu in Gnome, ZapZap 3.0 is installed with flatpak.

![image](https://user-images.githubusercontent.com/95233098/179224231-32d148a2-98ba-4c93-9eb0-25fc5651f847.png)

![image](https://user-images.githubusercontent.com/95233098/179224462-546f3e2d-43f7-445d-a648-7acbbf452e32.png)

**Comment by rafatosta** [comment]
did you enable it in Settings?

**Comment by musiclover382** [comment]
Ooops, looks like I messed up, sorry!! 😅😅
However, "ZapZap window" is not really a descriptive option... Only those who know that the hamburger menu can be implemented when the window decorations are handled by zapzap will understand what "ZapZap window" implies. To make the option more discoverable, I'd consider organizing the options in another way. For example you could set the title to Window, then have a "Hamburger menu (Restart required)" option inside the Title bar buttons list. Although not as formally correct, this would help dumb users like me!

**Comment by rafatosta** [comment]
the idea is to keep this window the default and not use it by choice of the user. I forgot to set it by default 😅

**Comment by rafatosta** [comment]
Not everyone is used to looking at an app's available settings

**Comment by rafatosta** [comment]
I tried my best to make it look like Telegram
