### ISSUE TITLE
Pressing the hamburger menu or esc key while in the preferences should return to the main view

### ISSUE THREAD

**Issue by musiclover382** [rafatosta/zapzap#59]
This mostly a design choice, but I think this is the most obvious behavior. While we are in the preferences we only have 1 way to return to chats, and it's not so obvious (it took me some time to realize that the ZapZap tab returns to the chats).

**Comment by rafatosta** [comment]
Suggest any specific name, icon?
I will put the ESC to return

**Comment by rafatosta** [comment]
Returning would be the most obvious 😅🤣

**Comment by rafatosta** [comment]
[Pressing esc key return to the main view](https://github.com/rafatosta/zapzap/commit/5af9b5c1e6027483512f6be3e4e843ee9885dd0d)

**Comment by rafatosta** [comment]
![image](https://user-images.githubusercontent.com/18619894/179326863-638df3a4-fe83-4ee6-aae2-8aeb8174c71f.png)
