### ISSUE TITLE
Font rendering and link preview

### ISSUE THREAD

**Issue by vivantart** [rafatosta/zapzap#65]
Rafael,

De uns tempos pra cá, a maioria dos clientes linux passaram a ter problema em gerar a pré-visualização do link no chat.
No macOS, que também é um electron wrapper, funciona normalmente. Alguns devs parecem ter começado a corrigir nos seus clientes linux esse problema, mas sem dar muitas informações. Você poderia investigar isso?

Na versão flatpak as fontes não parecem renderizar muito bem, como acontece no Fedora, por exemplo. Elas são finas e um pouco borradas. Existe alguma forma de usar as fontes do sistema ou aprimorar isso?

**Comment by rafatosta** [comment]
Olá, 
Sobre os links notei que até no aplicativo android não está pré-visualizando ao enviar, apenas ao receber.
Sobre as fontes, já tentou dar zoom? Se não for o caso do zoom, então é algo relacionado ao gnome 42. 
Tente isso:
https://wiki.archlinux.org/title/GTK#Text_in_GTK_4_applications_is_blurry_or_renders_incorrectly

**Comment by vivantart** [comment]
> Olá, Sobre os links notei que até no aplicativo android não está pré-visualizando ao enviar, apenas ao receber. Sobre as fontes, já tentou dar zoom? Se não for o caso do zoom, então é algo relacionado ao gnome 42. Tente isso: https://wiki.archlinux.org/title/GTK#Text_in_GTK_4_applications_is_blurry_or_renders_incorrectly

Oi, Rafael!
Comigo no android tem funcionado, a minha solução tem sido enviar o link pra mim numa conversa comigo e no celular copiar e colar na conversa que eu quero enviar realmente com a pré-visualização.

Não pensei no zoom, boa sugestão! Eu tô no KDE, mas vou lá nos diretórios das configs ver isso.
Realmente no seu print está normal...

**Comment by rafatosta** [comment]
Vou investigar sim, valeu por reportar!

**Comment by rafatosta** [comment]
Aproveitando... os novos ícones simbólicos ficaram com o tamanho correto no KDE?
Como uso gnome acabei que não testei (esqueci na verdade kkk)

**Comment by vivantart** [comment]
> Aproveitando... os novos ícones simbólicos ficaram com o tamanho correto no KDE? Como uso gnome acabei que não testei (esqueci na verdade kkk)

Os da bandeja?

**Comment by vivantart** [comment]
![Screenshot_20220717_152027](https://user-images.githubusercontent.com/109477864/179419938-7f5d4ce7-59a8-4232-88fd-66c7199dff81.jpeg)
![Screenshot_20220717_153130](https://user-images.githubusercontent.com/109477864/179419940-2acd52ea-1384-4c6f-a402-eba035886a00.jpeg)

**Comment by rafatosta** [comment]
> > Aproveitando... os novos ícones simbólicos ficaram com o tamanho correto no KDE? Como uso gnome acabei que não testei (esqueci na verdade kkk)
> 
> Os da bandeja?

Sim, mas os simbólicos. Olha lá nas configurações

**Comment by rafatosta** [comment]
> O cliente whatsapp-desktop-linux e o seu lado a lado: ![Screenshot_20220717_152027](https://user-images.githubusercontent.com/109477864/179419938-7f5d4ce7-59a8-4232-88fd-66c7199dff81.jpeg)
> 
> A bandeja: ![Screenshot_20220717_153130](https://user-images.githubusercontent.com/109477864/179419940-2acd52ea-1384-4c6f-a402-eba035886a00.jpeg)

A única diferença que vejo é o formato da fonte, fora isso me parece tudo ok. A fonte SegoeUI é um pouco "achatada" em comparação com as outras.

**Comment by vivantart** [comment]
Verdade, perdão (risos).
![Screenshot_20220717_154258](https://user-images.githubusercontent.com/109477864/179420294-7d6f306d-aca5-417c-b21f-b7094b9fb49d.jpeg)

**Comment by vivantart** [comment]
> > > Aproveitando... os novos ícones simbólicos ficaram com o tamanho correto no KDE? Como uso gnome acabei que não testei (esqueci na verdade kkk)
> > 
> > 
> > Os da bandeja?
> 
> A única diferença que vejo é o formato da fonte, fora isso me parece tudo ok. A fonte SegoeUI é um pouco "achatada" em comparação com as outras.

Eu tô achando melhor agora, não sei se foi porque reinstalei, mas na primeira vez parecia um pouco desfocado.
Agora também só vejo a diferença da fonte...

**Comment by rafatosta** [comment]
> Verdade, perdão (risos). ![Screenshot_20220717_154258](https://user-images.githubusercontent.com/109477864/179420294-7d6f306d-aca5-417c-b21f-b7094b9fb49d.jpeg)

Parece ótimo!!

**Comment by rafatosta** [comment]
> > > > Aproveitando... os novos ícones simbólicos ficaram com o tamanho correto no KDE? Como uso gnome acabei que não testei (esqueci na verdade kkk)
> > > 
> > > 
> > > Os da bandeja?
> > 
> > 
> > A única diferença que vejo é o formato da fonte, fora isso me parece tudo ok. A fonte SegoeUI é um pouco "achatada" em comparação com as outras.
> 
> Eu tô achando melhor agora, não sei se foi porque reinstalei, mas na primeira vez parecia um pouco desfocado. Agora também só vejo a diferença da fonte...

Que ótimo =D

**Comment by vivantart** [comment]
Rapaz, notei um comportamento errático aqui.
Quando você clica com o botão direito num link, a opção "Copy link address" leva direto pro navegador

**Comment by rafatosta** [comment]
Ainda estou trabalhando nesse menu por causa das correções ortográficas. Vi aqui e essas opções serão ocultadas depois.

**Comment by rafatosta** [comment]
Até hoje não achei uma solução pra isso. =/

**Comment by vivantart** [comment]
> Até hoje não achei uma solução pra isso. =/

É um mistério mesmo... Eu vi um único dev que colou no changelog um bugfix pra isso, mas eu não testei o app dele.
Vou dar uma olhada aqui e retorno. Vou testar em outros lugares e também no Windows pra ver se é algo relacionado a alguma biblioteca no linux.

**Comment by rafatosta** [comment]
Manda o nome do app, por favor.

**Comment by vivantart** [comment]
https://github.com/eneshecan/whatsapp-for-linux/releases/tag/v1.4.4

**Comment by vivantart** [comment]
Ah, cliquei agora no issue relacionado, mas ele fechou por ser algo relacionado ao próprio Whatsapp Web.
Só não faz sentido ele relatar como bug fix.

**Comment by rafatosta** [comment]
Exatamente. Olhei o código e não há nenhuma modificação pra esse tipo de problema. 
Eu tentei todo o tipo de permissão e não funcionou. Concluí que é algo relacionado ao whatsapp.

**Comment by vivantart** [comment]
O estranho é que no MacOS funciona, eu tenho uma partição com ele e logo testei pra saber se era algo universal.
No Linux/Windows, tanto no chrome quanto no firefox não funciona a pré-visualização.

Achei aqui agora uma notícia sobre isso e tem um trecho assim: 
**"It is still not possible to generate link previews on WhatsApp Web, since this is one of the unsupported features after the migration to multi-device, such as the ability to create broadcast lists or view live location on linked devices"**

**Comment by vivantart** [comment]
No FAQ do Whatsapp consta o seguinte trecho:

![Screenshot_20220722_185128](https://user-images.githubusercontent.com/109477864/180573387-dc4f5248-e3c7-4dbc-a408-f59298a687f7.jpeg)

**Comment by rafatosta** [comment]
Então o que nós resta agora é esperar o whatsapp suportar esse serviço. Obrigado 🙂
