### ISSUE TITLE
IMPOSSIBLE TO USE ON FEDORA SINCE UPDATE

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [rafatosta/zapzap#69]
![image](https://user-images.githubusercontent.com/45184918/180574050-ae6fca50-5639-4844-a607-1b37b6324d55.png)

**Comment by rafatosta** [comment]
Press F5

**Comment by jojojojojoj5564656465465** [comment]
Wahou amazing

Le sam. 23 juil. 2022, 00:18, Rafael Tosta ***@***.***> a
écrit :

**Comment by rafatosta** [comment]
Unfortunately this is a problem with WhatsApp itself, I try to get around but sometimes happens

**Comment by rafatosta** [comment]
I will leave an open issue explaining when this error happens.Thanks
