### ISSUE TITLE
Design a new icon for ZapZap

### ISSUE THREAD

**Issue by thalesruan** [rafatosta/zapzap#70]
Hi, I was thinking of a new icon for ZapZap, preferably by Gnome HIG. So I had some ideas and I made some sketches.
I thought to make something that remembers WhatsApp official icon(a green and circular speach bubble), but with more personality and better designed.  I made the "arrow" with a wrong position(right) in some sketches, but left is the correct way. This is some fast sketches, hope you like.

![photo_2022-07-24_13-52-26](https://user-images.githubusercontent.com/7895807/180657987-91dc5bae-9e4e-4d1c-bc32-d8e8a993f607.jpg)
![photo_2022-07-24_13-52-30](https://user-images.githubusercontent.com/7895807/180657989-6b6c5ed7-2201-44d8-a432-8ba76dbf1eb6.jpg)

**Comment by thiagojack** [comment]
Hello!
I'm not designer, but I like to do designs like a hobby. If you like anyone of this logo and need to edit something, say what you want and I will try to do on my spare time.
![zapzap_icon01](https://user-images.githubusercontent.com/5920212/180773695-3170d35b-61d8-46a1-838b-045388c85f77.png)
![zapzap_icon02](https://user-images.githubusercontent.com/5920212/180773699-446f9861-7719-49f2-8263-2aeb42ed0ca5.png)
![zapzap_icon03](https://user-images.githubusercontent.com/5920212/180773702-bd884d66-b7ba-47fc-879f-28d707e7494e.png)
![zapzap_icon04](https://user-images.githubusercontent.com/5920212/180773705-7caa027b-4ffb-477a-b044-1a0c72bae31d.png)
