### ISSUE TITLE
BUG: Mouse scroll up and scroll down not working

### ISSUE THREAD

**Issue by MatheusIam** [rafatosta/zapzap#72]
After the program is minimized and maximized a few times, the mouse wheel stops working properly... By the way, I test with another mouse and have noticed the same thing, so I try the trackpad scroll and it works!

**Comment by MatheusIam** [comment]
EDIT: Pressing F5 does not solves the problem

**Comment by rafatosta** [comment]
Oi, Matheus.
Não consegui reproduzir esse bug aqui. 
Qual DE está utilizando e tem como gravar um pequeno vídeo mostrando?

**Comment by MatheusIam** [comment]
Olá amigo, não precisa mais! Reiniciei a máquina e resolveu o problema.
DE: Gnome 42.2
A propósito, a lentidão em abrir links é normal?

**Comment by rafatosta** [comment]
Que bom que "resolveu" o problema. 
Defina lentidão? 
O whatsapp não abre links, apenas envia para o navegador padrão o link.

**Comment by MatheusIam** [comment]
O bug não "resolveu" :/
https://youtu.be/2e1NFrjy_kA

**Comment by rafatosta** [comment]
> O bug não "resolveu" :/
> Ja envio o link do video
> 

Está usando o tiling?

**Comment by MatheusIam** [comment]
Não to usando tiling
Vídeo: https://www.youtube.com/watch?v=IapVYBQduVU

**Comment by rafatosta** [comment]
Entendi o bug, mas não consegui reproduzir aqui. De qualquer forma ativei duas flags que age no focus e scroll da página.

**Comment by rafatosta** [comment]
Rodei o PopOS aqui e também não consegui reproduzir o problema. 
Sem a janela está maximizada o problema também acontece? @MatheusIam
