### ISSUE TITLE
versão 3.2.1 quebrou funcionamento com wayland

### ISSUE THREAD

**Issue by aleprovencio** [rafatosta/zapzap#78]
Tudo certo?

Acabei de fazer o upgrade e percebi que o `zapzap` parou de funcionar, a saída padrão mostra que ele tenta forçar o uso do plugin `xcb` ao invés de `wayland` ou `wayland-egl` para `QT_QPA_PLATFORM`.

A solução momentânea foi fazer o downgrade pra versão anterior.

**Comment by rafatosta** [comment]
Tudo na paz.
Você forçou no Flaseal o wayland?
O ZapZap não funciona no wayland e por isso não vem por padrão.

**Comment by rafatosta** [comment]
Executando com as configurações padrão e está tudo ok!

![image](https://user-images.githubusercontent.com/18619894/182367300-edcc48fe-f494-402a-8093-32f560127b6e.png)

**Comment by rafatosta** [comment]
Cara, não é uma indireta pra você não. É que várias pessoas estão vindo reclamar de mal funcionamento depois que alteram essa opção. Então só estou avisando que é um problema conhecido e para discutirmos sobre o assunto do wayland.

**Comment by rafatosta** [comment]
> Tudo certo?
> 
> Acabei de fazer o upgrade e percebi que o `zapzap` parou de funcionar, a saída padrão mostra que ele tenta forçar o uso do plugin `xcb` ao invés de `wayland` ou `wayland-egl` para `QT_QPA_PLATFORM`.
> 
> A solução momentânea foi fazer o downgrade pra versão anterior.

Esse problema apareceu porque "esqueci" de tirar a flag que libera o wayland rsrs

**Comment by aleprovencio** [comment]
Legal que descobriu! Podemos ter um novo release? :smiley:

**Comment by rafatosta** [comment]
De qualquer forma, sugiro utilizar as configurações padrão.
