### ISSUE TITLE
Zapzap doesn't work Wayland

### ISSUE THREAD

**Issue by rafatosta** [rafatosta/zapzap#79]
Sei que muitos estão animados com o Wayland e querem de qualquer forma deixar de usar o X11 nos aplicativos.
Porém, há uma limitação no ZapZap que **não funciona corretamente** e por isso **não tem suporte por padrão ainda**.
**Altere a permissão pelo Flatseal por sua conta em risco.**

Gostaria de saber a opinião de vocês usuários sobre a necessidade de um "WebApp" rodar em Wayland ao invés de XWayland.

I know many are excited about Wayland and want to stop using X11 in the applications.
However, there is a limitation on ZapZap that **does not work correctly** and therefore has no **support by default yet**.
**Change permission by Flatseal at your own at risk.**

I would like to know your opinion users about the need for a "WebApp" running in Wayland instead of Xwayland.

**Comment by aleprovencio** [comment]
Vai ter que ser eu pra começar né ....rsrs

Vamos lá:

* `Wayland` é de fato o novo padrão de `DSP` para Linux, contruído principalmente com foco em segurança e hoje já vem por padrão nas distros mais relevantes, além de ser planejado a transição para a maioria das que ainda não adotam.
* `X11` como muitos dizem é 'impossível de se fazer seguro' especialmente por não suportar chamada 'GUI isolation'; Já faz um tempo que seu desenvolvimento está em modo manutenção, enquanto os esforços estão sendo concentrados no `Wayland`.
* `XWayland` é meramente um `X Server` rodando no `Wayland` para prover compatibilidade para aplicações `X11` legadas.
* `Flatpaks` se beneficiam imensamente da arquitetura `Wayland` e várias outras tecnologias da stack `freedesktop`.
* Usuários vão cada vez vez mais querer usar tecnologias como `Wayland`, `Flatpaks`, etc assim como cada vez menos `X11/XWayland`.
* O `zapzap` tem uma base de código relativamente pequena e pouco dependente de X11 e apesar de ser 'apenas um webapp', mesmo que indiretametente pelos motivos acima, vai se beneficiar desta padronização.

Então na minha humilde opinião, o ideal seria adotar o padrão Wayland e caso necessário deixar uma opção de fallback para Xwayland.

**Comment by rafatosta** [comment]
Acredito que pela minha ignorância no assunto e por ser um simples WebApp como "Wayland é novo e só, quero usar e pronto".

A execução em wayland funciona bem e só há um único velho conhecido bug, a Tray. Só não deixo por padrão porque não sei qual o impacto para os usuários de outras DE, pois uso o gnome.

Se executar em wayland notará que não terá mais ícone na tray (pelo menos no gnome) e o seguinte erro:
`qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)`

Como estava ocupado com minhas atividades e na inclusão das funcionalidades não verifiquei se o mesmo acontece em outras DEs (pelo menos no Plasma, pois não tem como verificar todas)

**Comment by aleprovencio** [comment]
No meu sistema com `sway` com os portais `wlr` e `gtk` instalados, simplesmente não tenho problema algum com o ícone da tray... (rodando a penúltima versão do zapzap, em wayland)

Posso estar errado mas acho que este problema que está dizendo é devido à alguma configuração de variável de ambiente ou mesmo os portais corretos instalados.
