### ISSUE TITLE
Filename does not come automatically while downloading (save as) a file.

### ISSUE THREAD

**Issue by paulolezak** [rafatosta/zapzap#80]
Quando baixa um arquivo  ele não sugere o nome do arquivo.

**Comment by rafatosta** [comment]
Isso é uma limitação do flatpak, infelizmente não achei uma solução para isso.

**Comment by eduardomozart** [comment]
Isso acontece tambem no aplicativo oficial do WhatsApp para macOS, acredito que no Windows tambem aconteca. Não da nem pra especificar onde voce^ quer baixar o arquivo no macOS, ele sempre baixa para a pasta Downloads. Se nem o desenvolvedor do aplicativo conseguiu encontrar uma solucao, quem dira no's, meros mortais, hehe.

**Comment by rafatosta** [comment]
O máximo que conseguir fazer foi colocar a extensão do arquivo caso não seja colocado.

**Comment by paulolezak** [comment]
@eduardomozart , não estava me referindo em qual pasta ele vai salvar..  mas sim, o nome do arquivo.  
Ex : recebo arquivo  "contrato.pdf"  vou baixar para o computador,  eu tenho que digitar o nome do arquivo e extenção pq ele não preenche nada..  

Bom.. acredito que injetar um js dentro do navegador do app pra capturar o evento e nome do arquivo consiga pegar o nome do arquivo pra não precisar digitar..  

Apesar dos pequenos detalhes. esse é o melhor app whatsapp que testei pra linux..   parabéns @rafatosta

**Comment by rafatosta** [comment]
Como disse antes: **é uma limitação do flatpak**.
Tenho acesso ao nome do arquivo e a extensão, por algum motivo que desconheço, o flatpak não carrega o nome do arquivo na janela. 

Para amenizar um pouco isso não é preciso mais escrever o nome da extensão, pois já é inserida automaticamente ao salvar. 

Muito obrigado pelo reconhecimento.

**Comment by eduardomozart** [comment]
@paulolezak Não apenas não é possível especificar onde você quer salvar, também não é possível especificar o nome do arquivo. Essa limitação existe tanto no ZapZap quanto no aplicativo oficial do WhatsApp Desktop.

**Comment by rafatosta** [comment]
Gente, é um limitação do **Flatpak** e não do ZapZap. 
Ter a informação de forma correta é bom para todos na hora de propagar ou entendimento do problema.
