### ISSUE TITLE
Seletor de arquivo para upload não reflete tema da distro

### ISSUE THREAD

**Issue by eduardomozart** [rafatosta/zapzap#83]
Boa noite, Rafael
Apenas uma dúvida. Abri um Bug Report lá na página da Distro (https://github.com/linuxdeepin/developer-center/issues/3357), mas talvez você já tenha encontrado esse erro antes.
Compilei o ZapZap através do código fonte, mas ao selecionar um arquivo para upload, o tema do seletor de arquivo não corresponde ao do sistema operacional. Uso o tema Dark e a janela de seleção de arquivo é White.
Você já encontrou esse erro antes? Tem algo que possamos definir nos argumentos através do Flatseal para forçar o tema Dark? O próprio App tem o seletor de tema, selecionei o tema Dark, mas aparentemente ele não está aplicando no File Chooser do PyQt.
![Capturar_zapzap_20220802212805](https://user-images.githubusercontent.com/2974895/182500029-4bcfb6eb-758f-47d9-82f4-259e63594d59.png)

**Comment by rafatosta** [comment]
O app não controla o tema das aplicações externas,  nem do seletor de arquivo e não há nenhuma "informação" sobre tema passado, apenas pede para o sistema que abra o seletor de arquivo através do QFileChooser.

**Comment by rafatosta** [comment]
Problema da distro, Ver #76

**Comment by herzenschein** [comment]
Este erro ocorre no Ubuntu também. Creio que descobri a razão.

Explicando do zero:

* A janela de diálogo que está com problema de tema é do Qt, não a nativa do sistema
* A janela de diálogo nativa utiliza o tema correto
* Para utilizar a janela de diálogo nativa, é necessário usar o xdg-desktop-portal
* Para isso, basta seguir as [diretrizes de integração do Qt pro flatpak](https://docs.flatpak.org/en/latest/portals-qt.html), coisa que já está sendo feita
* Mas o ZapZap utiliza Qt6, que não está em todas as distros ainda
* Nessas distros não há suporte a apps Qt6 no xdg-desktop-portal
* Logo, o ZapZap não exibe automaticamente a janela de diálogo correta

Este mesmo problema também ocorre com o Telegram, que migrou pro Qt6.

O ZapZap exibe a janela de diálogo correta no meu Fedora Rawhide (37), mas não em distros como as versões do Ubuntu que não tem Qt6.

Solução temporária: para manualmente forçar o uso do portal para utilizar o tema correto, use:

    QT_QPA_PLATFORMTHEME=flatpak flatpak run com.rtosta.zapzap

Ou melhor ainda, salve a variável de ambiente para não ter que rodar toda vez:

    flatpak override --env="QT_QPA_PLATFORMTHEME=flatpak" com.rtosta.zapzap

(precisa de sudo caso vc tenha instalado o flathub sem --user)

**Comment by rafatosta** [comment]
O que acontece com a definição dessa variável em distribuições que estão funcionando?
Se não afetar posso torná-la padrão.

**Comment by herzenschein** [comment]
Pelo que testei, não parece causar nenhum problema, continua usando o portal do mesmo modo.

Posso perguntar lá no grupo do #flatpak no Matrix depois.

**Comment by herzenschein** [comment]
Aliás, já que já está no flathub, deve ser possível criar um issue por lá e pingar o pessoal do flatpak por lá para confirmar, tipo o hfiguiere, barthalion ou o nedrichards.
