### ISSUE TITLE
Notificação não exibe ícone do ZapZap

### ISSUE THREAD

**Issue by eduardomozart** [rafatosta/zapzap#84]
Oi Rafa,
Antes de abrir um bug na página da Distro, acho que pode não ser bug da Distro, mas talvez a ausência do ícone ou o caminho seja diferente quando o ícone é compilado manualmente ao invés de usar o Flatpak, mas quando recebo novas mensagens, o ícone do ZapZap não é exibido, é exibido o ícone padrão de notificações do Deepin ao invés do ZapZap.
![Capturar_select-area_20220802213222](https://user-images.githubusercontent.com/2974895/182500235-40363c1a-018a-46e9-aeb7-0e9a671ac081.png)

**Comment by rafatosta** [comment]
Oi, Edu. 
Esse ícone deveria mostrar a imagem do contato. 
A imagem é salva dentro da pasta de dados do ZapZap (~.local/share/ZapZap/tmp). Verifica se tem algum conteúdo nela. 

Mais cedo analisei a distro que você está utilizando e pude notar que há uma certa incompatibilidade com o dbus, que é justamente o problema do flatpak. A minha conclusão parcial, por isso ainda não dei um retorno aos seus problemas, é que a distro não segue alguns padrões, ou seja, possui sua própria implementação e com isso está quebrando as funcionalidades do aplicativo mesmo pelo código fonte.

Não querendo jogar um banho de água fria, mas tudo indica que as personalizações/implementações do Deepin impossibilita do app funcionar. Pois esses problemas são justamente na interação app -> sistema. 
Lembrando que usei o padrão definido pelo [FreeDesktop](https://www.freedesktop.org/wiki/) que é utilizado pelas distros linux (pelo visto a maior parte delas).

**Comment by eduardomozart** [comment]
Sim, o Deepin tem um visual bem diferente e em algumas coisas foge do padrão ou ainda não foram implementados na Distro, mas a cada Release a Distro vem se tornando mais estável. Na China, o Deepin já acompanha os notebooks da Huawei por padrão, então apesar de não ser uma distro muito conhecida por aqui, está começando a ganhar destaque entre os fabricantes de PCs na China.
Sei que as notificações do Deepin suportam também ícones personalizados, já que as notificações do sistema usam ícones personalizados. Vou ver se mexo no código fonte do ZapZap e consigo fazer as imagens aparecerem.
Obrigado pela resposta, já me deu um ponto de partida para começar!
Abraço!

**Comment by rafatosta** [comment]
Será que é por ter pacotes muitos antigos por causa da base Debian?

**Comment by eduardomozart** [comment]
Encontrei um único arquivo .yaml no diretório ``_packaging/flatpak/com.rtosta.zapzap.yaml``, mas ele não parece ter nenhuma referência a versão do DBus.
Antigamente o Deepin era baseado no Debian Unstable, mas desde que fizeram a parceria com as fabricantes de PC chinesas, passaram a usar a base Debian Stable. Só os aplicativos Flatpak, Snap e AppImage salvam, kkkk XD Mas gosto da base Debian, é bem estável e leve em geral. O APT-Cache reporta que a versão 1.12.20 do DBus está instalada:

``
$ apt-cache policy dbus
dbus:
  Instalado: 1.12.20-0+deb10u1+rebuild
  Candidato: 1.12.20-0+deb10u1+rebuild
  Tabela de versão:
 *** 1.12.20-0+deb10u1+rebuild 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
        100 /usr/lib/dpkg-db/status
``

**Comment by eduardomozart** [comment]
Aparentemente a versão está dentro dos requisitos mínimos, então é pra funcionar. Temos esperança kkkk Vou ver se consigo consertar e envio uma Pull Request.
