### ISSUE TITLE
Feature request: setting to open downloaded files directly

### ISSUE THREAD

**Issue by herzenschein** [rafatosta/zapzap#86]
My mother, who isn't quite tech literate, has been using the web version of Whatsapp on her Kubuntu machine for a while and I tried introducing ZapZap to her.

Her main complaint is that its behavior upon clicking a downloadable file is different: via web browser, a click downloads e.g. a PDF and automatically opens it in Okular; with ZapZap, she gets a Save File dialog instead, which she doesn't know how to handle very well yet.

Would be nice if there was a setting I could enable for her so that clicking downloadable files would open them instead of asking where to save them. I understand the security implications of such a feature.

From a brief search it seems the right Qt API for this would be QDesktopServices.

**Comment by rafatosta** [comment]
Com certeza estará na próxima versão. 

A ideia que tive foi:
- ao clicar no arquivo abre um diálogo perguntando se deseja abrir o arquivo ou salvar.
- a opção Abrir irá salvar o arquivo automaticamente na pasta download e abrir o arquivo.
- a opção de Salvar irá abrir a o Filechooser para escolher o local e o nome.

A forma de abrir mencionado já utilizo para abrir links no navegador padrão do sistema.
