### ISSUE TITLE
Language selection for spell checking

### ISSUE THREAD

**Issue by Leuug** [rafatosta/zapzap#87]
The app does spell checking, but only for English. It would be great to have an option to choose which language to spell check from, and preferentially, to choose more than one language to spell check from.

**Comment by Leuug** [comment]
UPDATE: it seems that if I set the system's language to a language other than English, the app spell checks for that language **and** for English, but if I set the system's language for English, it spell check **only** for English.

I only tested it for Portuguese.

**Comment by rafatosta** [comment]
Olá, tudo bem? 
Não sei se entendi direito o seu problema, mas a verificação ortográfica está presente para vários idiomas. 
Sim, só há suporte a um único idioma por vez e será o mesmo a linguagem do seu sistema. Ou seja, não vai ficar para inglês e português se seu sistema estiver em português por exemplo.

**Comment by Leuug** [comment]
Olá. Então, o problema é que eu uso meu sistema em inglês, mas quando uso o whatsapp, eu escrevo em português. Por isso gostaria de ter como selecionar o idioma que será usado para fazer spell checking sem precisar modificar o idioma do meu sistema inteiro.

**Comment by rafatosta** [comment]
Tudo indica que esse recurso estará disponível na versão 4.0 que será lançada ainda essa semana, porém preciso de ajuda para identificar os dicionários.

Segue os dicionários suportados pelo ZapZap.
[Dicionários disponíveis.txt](https://github.com/rafatosta/zapzap/files/9339754/Dicionarios.disponiveis.txt)

O que preciso é que coloque o nome em inglês das línguas após a vírgula. Exemplo:
![image](https://user-images.githubusercontent.com/18619894/184715818-f30d3753-0b88-447f-93cf-4662c1013925.png)

Agradeço a colaboração

**Comment by Leuug** [comment]
Feito:
[Dicionarios.disponiveis.txt](https://github.com/rafatosta/zapzap/files/9344058/Dicionarios.disponiveis.txt)

**Comment by rafatosta** [comment]
Falta fazer alguns ajustes na interface, mas está funcionando perfeitamente!
![image](https://user-images.githubusercontent.com/18619894/185010483-43d8d281-e61a-4d25-bd31-6b76cc70246c.png)

**Comment by rafatosta** [comment]
Por algum motivo faltou esses nomes na lista que extrair.
Você poderia acrescentar nesse aquivo aqui?
https://github.com/rafatosta/zapzap/blob/main/zapzap/services/spellCheckLanguages.py

Manda um pull request com o arquivo atualizado se quiser ou por aqui mesmo.
Valeu
