### ISSUE TITLE
Use SVG PayPal logo

### ISSUE THREAD

**Issue by musiclover382** [rafatosta/zapzap#88]
PayPal logo looks blurry in the readme, why not use a scalable version?

![261591EF-0F72-4F1B-B96B-F4D2FD2CA571](https://user-images.githubusercontent.com/95233098/184844996-466b5ec0-96e9-44f3-afd9-5e7f2eb5daa3.png)

https://upload.wikimedia.org/wikipedia/commons/b/b5/PayPal.svg

**Comment by rafatosta** [comment]
Thanks!
