### ISSUE TITLE
Atalho para fechar conversa atual

### ISSUE THREAD

**Issue by RoinujNosde** [rafatosta/zapzap#94]
![image](https://user-images.githubusercontent.com/6441328/185716756-3809a965-69d5-4ec6-a1e4-d98ea1c43567.png)
Seria possível adicionar um atalho que faz a mesma funcionalidade daquele botão? Talvez um Ctrl W.

**Comment by rafatosta** [comment]
Toda e qualquer manipulação na página pode ser feita através de comandos em Javascript. 

Se enviar um que execute essa funcionalidade na página posso criar um atalho.

**Comment by RoinujNosde** [comment]
Já tentei encontrar a função com o debug do navegador, mas sem sucesso. O js da página está ofuscado.

**Comment by rafatosta** [comment]
Essa função não pode ser **encontrada**, precisa ser **criada**.
Olha esse exemplo:  #85

**Comment by RoinujNosde** [comment]
https://greasyfork.org/en/scripts/443126-whatsapp-conversation-hider/code

Eu fiz esse código há um tempo. 
Só que a implementação não tá legal, tá simulando um clique em "Opções", depois no "Fechar conversa". Tem um delay também... 
Seria melhor uma função nativa do web, que está escondida em algum lugar.

**Comment by rafatosta** [comment]
Se executar diretamente o closeConversation() no console a conversa é fechada?

**Comment by RoinujNosde** [comment]
Sim

**Comment by RoinujNosde** [comment]
Dentro do closeConversation() tem mais um delay para esperar o menu abrir, se conseguir otimizar isso...

**Comment by rafatosta** [comment]
Quer implementar isso? 
Te digo aonde alterar (as alterações)

**Comment by RoinujNosde** [comment]
Pode falar :)

**Comment by rafatosta** [comment]
> Pode falar :)

1. Criar o Menu no MainWindow.ui
2. Criar uma função no MainWindow.py para emitir um sinal pra o zapHome para informar que tem um evento de fechar mensagem
3. Colocar o sinal em MenuBar() para chamar a função definida em 2
4. Criar uma função em zapHome. Essa função fará: 
- Pega a referencia da página atual
- Chama uma função referente ao container da página
- olhe a função reloadPage()
5. Criar uma função em UserContainer que acessará a pagina via page = self.browser.page() e emitirá a instrução em JS page.runJavaScript("")

**Comment by rafatosta** [comment]
Não se notou, mas pressionando ao visualizar uma imagem é como se apertasse em Download.
Tem como fazer alguma verificação sobre isso ou até fechar a visualização da imagem ao pressionar o atalho de fechar a conversa?

![image](https://user-images.githubusercontent.com/18619894/187475639-434e8818-d841-4d6e-be32-6dff47dd4121.png)

**Comment by RoinujNosde** [comment]
Acho que isso deve resolver:
```js
if (!getMoreOptions()) {
    return;
}
```

**Comment by rafatosta** [comment]
> Acho que isso deve resolver:
> 
> ```js
> if (!getMoreOptions()) {
>     return;
> }
> ```

Vou fazer o teste mais tarde. Valeu

**Comment by rafatosta** [comment]
Testei aqui e não funcionou. De qualquer vou lançar uma atualização hoje e aos poucos vamos ajustando isso.

**Comment by RoinujNosde** [comment]
Ah, não tinha entendido direito o problema. Mais tarde dou uma olhada.

**Comment by RoinujNosde** [comment]
![image](https://github.com/rafatosta/zapzap/assets/6441328/33cb361c-1f92-4021-9ac1-2c90c3b6c45c)
Será que esse atalho é recente? Nunca tinha reparado nisso.

Simplificaria e muito a lógica do closeConversation(), é só enviar o ESC para a página.

**Comment by rafatosta** [comment]
Também não reparei nisso. Simplifica bastante 🙌🏽🙌🏽

**Comment by rafatosta** [comment]
Funciona perfeitamente. Já fiz o teste e vou mandar um PR e mandar a atualização para o flathub. Valeu!

**Comment by rafatosta** [comment]
Na verdade, todos os atalhos estão funcionando sem qualquer interferência minha. Como o ESC foi sobrescrito para ser executado ao fechar, então precisou ser reimplementado.
